msupply-foundation/conforma-web-app

src/containers/Application/ApplicationPage.tsx, src/utils/generated/graphql.tsx, src/utils/graphql/queries/getApplication.query.ts, src/utils/hooks/useGetResponsesByCode.tsx, src/utils/hooks/useLoadTemplate.tsx, src/utils/types.ts
Fixes #35.
This PR is a replacement for #49 as it has been refactored to be based on #54.
=> 35(2) Response object hook

src/utils/generated/graphql.tsx, src/utils/graphql/mutations/createApplication.mutation.ts
Very small addition to @nmadruga's work -- just added the Trigger to the Application Create query. Needed to make my back-end Actions work ([this PR](https://github.com/openmsupply/application-manager-server/pull/94))
=> Add OnApplicationCreate trigger

src/utils/helpers/getSectionsPayload.tsx
Something that was missing from previous work. Fix order of sections.
=> Fix order of sections

src/formElementPlugins/dropdownChoice/src/ApplicationView.tsx
=> #243 Make DropDown option key unique

src/index.tsx
Fixes #118
Followed instructions in: https://www.apollographql.com/docs/react/networking/authentication/#header.
Then checked in inspector and saw this:
Then checked against back end row lvl policy restrictions branch and it seems to work:
https://github.com/openmsupply/application-manager-server/pull/174
=> JWT is used for GraphQL for existing queries

src/containers/Application/ApplicationCreate.tsx, src/utils/generated/graphql.tsx, src/utils/graphql/mutations/createApplication.mutation.ts, src/utils/graphql/mutations/updateApplication.mutation.ts, src/utils/hooks/useCreateApplication.tsx
Very small update --  adds optional variables `userId` and `orgId` to createApplication mutation, and ensures that those values are passed through from ApplicationCreate.tsx
=> #297 Fix CreateApplication mutation

documentation/internal/Overview-of-Navigation-&-URL-structure.md
Fixes #269 
Fixes #282
Most of the documentation is done at back end
Links to back end would require this branch to be merged on back end: https://github.com/openmsupply/application-manager-server/pull/209
=> Review and consolidation documentation

src/containers/Application/ApplicationPage.tsx, src/containers/Application/ApplicationWrapper.tsx, src/containers/Application/index.ts, src/utils/generated/graphql.tsx
This is a pretty bare-bones skeleton for the Page container. Will need to be updated as ProgressBar, Validation, Navigation components are implemented.
**NOTE**: I have branched from #359, but I've also merged in #358 (as I needed the Status), so probably need that one to be merged to master first, otherwise the diff here will include #358's changes. (Changes specific to this issue are mainly in "ApplicationWrapper" and "ApplicationPage")
Re-direction based on Status is working, and the FullStructure is loaded.
See ApplicationFlow diagram for what is implemented (coloured green). Let me know if there's any additional functionality that should go into this PR.
=> #346 Create ApplicationPage container

src/containers/Application/ApplicationHome.tsx, src/containers/Application/ApplicationPage.tsx, src/utils/hooks/useGetFullApplicationStructure.tsx, src/utils/types.ts
Implements #347 -- validation happens along with evaluation of visibility, etc. Haven't implemented any logic outside this hook -- @andreievg is working on that.
I'm not actually 100% clear on how it's handling undefined/null responses -- it should really also consider whether question is required and visible, will need to clarify that.
=> #347 Validation in useGetFullStructure hook

src/components/Application/ApplicationStart.tsx, src/components/Application/Sections/SectionsList.tsx, src/components/Application/Sections/SectionsProgress.tsx, src/components/Application/Sections/index.ts, src/components/Sections/SectionsList.tsx, src/components/Sections/index.ts, src/containers/Application/ApplicationCreateNEW.tsx, src/containers/Application/ApplicationHome.tsx, src/containers/Application/index.ts, src/containers/Main/SiteLayout.tsx, src/utils/helpers/structure/buildSectionsStructureNEW.ts, src/utils/hooks/useLoadTemplate.tsx, src/utils/hooks/useLoadTemplateNEW.tsx, src/utils/types.ts
Fixes #368 
- ~~#375~~ MERGED
- Create new `ApplicationCreate` and link to path [localhost:3000/applicationNEW/new?type=ReviewTest](http://localhost:3000/applicationNEW/new?type=ReviewTest)
- Create simply component to only list sections in the list with empty circle icon on the left
- Remove unused method `buildTemplateSectionsStructure` in the new file since that's not used in new `useLoadTemplate` which only returns the list of **SectionDetails** for each section to be displayed in ApplicationCreate
- After `useLoadTemplate` returns template details, in **useEffect** check if there is no `startMessage` and just call the `handleCreate` method straight away -> Which redirects to the first page of the new application after creation.
- OR if `startMessage` is defined will run the evaluator …
=> #368 New application create page

src/containers/Review/ReviewHome.tsx, src/containers/Review/ReviewOverview.tsx, src/containers/Review/ReviewPage.tsx, src/containers/Review/ReviewPageWrapperNEW.tsx, src/containers/Review/ReviewSectionAssignment.tsx, src/containers/Review/ReviewWrapper.tsx, src/utils/generated/graphql.tsx, src/utils/graphql/queries/getReviewAssignment.query.ts, src/utils/graphql/queries/getReviewNEW.query.ts, src/utils/helpers/review/getAssignedQuestions.ts, src/utils/helpers/structure/generateReviewProgress.ts, src/utils/hooks/useCreateReview.tsx, src/utils/hooks/useGetFullApplicationStructure.tsx, src/utils/hooks/useGetFullReviewStructure.tsx, src/utils/hooks/useGetReviewAssignment.tsx, src/utils/hooks/useGetReviewInfo.tsx, src/utils/hooks/useLoadApplicationNEW.ts, src/utils/types.ts
branched from #380-review-page-part-2
* adjusted hooks as per diagram: (https://app.diagrams.net/#G1EANnshpdQMk-uCXr7FMrRqIY-ESytIYV), see left part
* added review question assignment to review response when review is created
* added `ReviewHome` -> get full structure and iterates over sections to insert `ReviewSectionAssignment`
* added `ReviewSectionAssignment` -> not happy with this name, it's a component that renders a row of Section/Assignment
I used back end branch #277FE-decision-area
go to review page (with new and the old way)
add review with old way, and change it with new way and see how ReviewHome in the new way changes
=> #379 review home part 1

src/utils/generated/graphql.tsx, src/utils/graphql/queries/getReviewInfo.query.ts, src/utils/hooks/useGetReviewInfo.tsx, src/utils/types.ts
Fixes #428 
To be merged with [Back-endPR#249](https://github.com/openmsupply/application-manager-server/pull/249)
=> #428B Update query and type to use review timeStatusCreated field

src/formElementPlugins/ApplicationViewWrapperNEW.tsx, src/formElementPlugins/SummaryViewWrapperNEW.tsx, src/utils/helpers/structure/addEvaluatedResponsesToStructure.ts, src/utils/hooks/useLoadApplicationNEW.ts, src/utils/hooks/useLoadTemplateNEW.tsx
Fixes #484 
Adds GraphQL connection object to front-end for dynamic parameter lookups.
Requires back-end branch from [this PR](https://github.com/openmsupply/application-manager-server/pull/276) to see it in action -- Company lookup on Page 3 (Section1)
=> #484 GraphQL connection fix

src/utils/generated/graphql.tsx, src/utils/graphql/mutations/createReview.mutation.ts
fixes: #609 (review part, back end PR to fix application part to follow)
Changes as per: https://github.com/openmsupply/application-manager-web-app/issues/609#issuecomment-819144762
=> #609-fix-start-review-404-bug

src/components/Review/ReviewSectionRowLastActionDate.tsx, src/utils/generated/graphql.tsx, src/utils/graphql/mutations/updateReviewAssignment.mutation.ts, src/utils/graphql/queries/getReviewInfo.query.ts, src/utils/hooks/useGetReviewInfo.tsx, src/utils/hooks/useUpdateReviewAssignment.tsx, src/utils/types.ts
Fixes #573.
Requires [back end PR #304](https://github.com/openmsupply/application-manager-server/pull/304)
Very minor change, fairly sure it covers everything. Any ideas where else it might be used in front-end? (I dealt with all the compilation errors, so there shouldn't be any more probs, right?)
=> #573 Replace timeCreated with timeUpdated

src/formElementPlugins/fileUpload/src/ApplicationView.tsx, src/utils/generated/graphql.tsx
#576 
Small tweak to only show the button if file count is less than the limit.
=> #576 Hide Upload button if fileCountLimit reached

src/formElementPlugins/fileUpload/src/ApplicationView.tsx
Quick fix for issue mentioned in [this comment](https://github.com/openmsupply/application-manager-web-app/issues/576#issuecomment-823742869)
=> #576 (2) Fix for when fileCountLimit is not defined

src/components/Home.tsx, src/containers/Application/ApplicationCreate.tsx, src/containers/Application/ApplicationHome.tsx, src/containers/Application/ApplicationPage.tsx, src/containers/Application/ApplicationSummary.tsx, src/containers/List/ListWrapper.tsx, src/containers/Review/ReviewWrapper.tsx, src/utils/constants.ts, src/utils/hooks/usePageTitle.ts, src/utils/hooks/useRouter.tsx
Fixes #655 and #625 (Page titles).
As discussed with @andreievg
=> #655 Re-direct push/replace in list

src/formElementPlugins/password/pluginConfig.json, src/formElementPlugins/shortText/pluginConfig.json, src/formElementPlugins/shortText/src/ApplicationView.tsx
need a better solution i think, and an issue, quick replication of what is fixed with this issue -> try editing user details
=> fix default values for password and shortText

documentation/internal/Element-Type-Specs.md, src/formElementPlugins/search/src/ApplicationView.tsx
Added this quick fix to demo branch, so just making quick PR so we don't forget to add it back to the main branch.
TO-DO:  Update docs
=> Update textFormat for Search plugin

src/components/PageElements/PageElements.tsx, src/containers/Review/ReviewPage.tsx
Fixes #859 
Fixes #861 
- Based on PR #845 
- Backend PR https://github.com/openmsupply/application-manager-server/pull/471
TODO
=> #859 fix app breaking with half consolidation misconfiguration

src/formElementPlugins/ApplicationViewWrapper.tsx
Fixes #869.
I'm not entirely sure why this is necessary. Basically, the "checkboxes" array in Checkbox ApplicationView was triggering the useEffect every time the parameters were re-evaluated (i.e. on response changes), even when it hadn't changed its value(s). Which was in turn triggering a re-calculation of the checkboxElements objects and re-saving the response, causing an infinite loop.
I've added a value equality check to the Wrapper before updating the evaluatedParameters, which seems to prevent this loop (I did it in the Wrapper so it would also work for any other affected plugins), but it seems a bit hacky to have to manually check for changed values when React normally takes care of that for us.
=> #869 Checkboxes bug fix

.github/workflows/build_docs_site.yml, .gitmodules, docs/public/config.toml, docs/public/content/_index.md, docs/public/content/developers/_index.md, docs/public/content/developers/introduction.md, docs/public/content/getting-started/_index.md, docs/public/content/getting-started/applicants/_index.md, docs/public/content/getting-started/introduction.md
Fixes #891.
See https://openmsupply.github.io/application-manager-web-app/.
<s>Note: reset default branch to `master` after merging!</s>
=> #891 add minimal public zola docs

.github/workflows/build_docs_site.yml
Fixes: #901 
Haven't tested, would assume it would work when merged to master.
@wlthomson how does this look ?
=> #901 only fire action on master branch push

src/components/Main/Footer.tsx, src/config.ts
Needs back end branch in this PR: https://github.com/openmsupply/application-manager-server/pull/502
I've added this to demo-08-08-2021 branch (current demo server branch).
Commit should  pretty straight forward.
=> add version to build

src/formElementPlugins/radioChoice/src/ApplicationView.tsx
Fixes #893
I think I must have removed this line for the "onSave" condition when I was last updating the default-saving on first load issue.
Good spotting, @nmadruga -- thanks!
=> #893 Radio button default fix

docs/internal/Element-Type-Specs.md, src/formElementPlugins/checkbox/src/ApplicationView.tsx
Fix #905 
Small additional to the response object to make it easier to query dynamic options lists.
=> #905 Add selectedValuesArray to response

src/containers/TemplateBuilder/template/Permissions/Permissions.tsx
Fixes: #915 
Assign template permissions to have level 1
=> 915 assign permission to have level when editing with template builder

docs/internal/demo-server-guide.md
Just quickly added this doc for updating the demo server.
=> Demo server guide

src/utils/generated/graphql.tsx, src/utils/graphql/fragments/fullTemplate.fragment.ts
Fixes #951.
As per issue description, changes as per commit.
Try loading basic snapshot (from this repo, haven't tries from other repo), and try to configure org registration template. Do the same with this fix.
=> #951 TB to ignore is config applications that are stuck in processing

src/containers/TemplateBuilder/template/Form/Pages.tsx
Just a small tweak fior Template builder - no issue made in a rush
=> Keep selected page while moving up or down on the list of pages

src/containers/Application/ApplicationSummary.tsx, src/utils/constants.ts, src/utils/generated/graphql.tsx
Fixes #879
##Linked PR 
Based on PR #984 
Very quick adding to help with linked application of outcomes to have better title - Completed application
Application before submission:
Application after submission:
=> #879 Show different title when application is completed

src/config.ts
Fix by Andrei. Prior to release beta B-1.0.8
=> Dont append api to graphql queries in production

package.json, src/containers/Dev/Snapshots.tsx, src/containers/TemplateBuilder/evaluatorGui/guiDefinitions.tsx, yarn.lock
Fix #1142 
- update evaluator version (was missing an Operator Type)
- Add "objectFunctions" operator to GUI
- Add "POST" operator to GUI
- Tidy up existing operators in GUI
Edit: Also added a small fix to refresh the Snapshots list after saving a new one (something that's been annoying me for a while) -- c53d18ea
=> #1142 Missing operators in template builder

src/formElementPlugins/fileUpload/src/ApplicationView.tsx
Fix #1146 
Very simple -- just use "serial" from applicationData rather than URL parameters. No idea why I didn't do it like this the first time. 🙄
=> #1146 File upload template builder fix

src/containers/User/Login.tsx, src/contexts/UserState.tsx
Fix #1162 
Putting this PR in draft for now, as I'm not sure that this will fully solve the problem, for reasons I mentioned in [this comment](https://github.com/openmsupply/application-manager-web-app/issues/1162#issuecomment-1111540317).
I don't think the changes here will do any harm, but I wouldn't like to say the problem is fully fixed. But I haven't been able to reproduce it lately, with or without this PR.
Further discussion required, but please try and note the conditions next time we see this problem.
=> #1162 clear apollo cache on logout

semantic/src/site/globals/site.overrides, src/containers/TemplateBuilder/template/Permissions/PermissionNameInfo/InfoComponents.tsx, src/containers/TemplateBuilder/template/Permissions/PermissionNameInfo/PermissionNameInfo.tsx, src/containers/TemplateBuilder/template/Permissions/PermissionNameList.tsx
=> 1173 Tidy up permissions info modal

package.json, src/containers/Review/ReviewSubmit.tsx, src/containers/Review/assignment/AssignmentRows.tsx, src/containers/Review/assignment/AssignmentTab.tsx, src/containers/Review/assignment/useGetAssignmentOptions.ts
closes: B/E https://github.com/openmsupply/application-manager-server/issues/738
B/E PR: https://github.com/openmsupply/application-manager-server/issues/738
A couple of small fixes, as per commits
=> BE 738 Final decision and assignment fixes

src/containers/TemplateBuilder/shared/OperationContextHelpers.tsx
Closes #1185 
Ah, no more clutter (well, less anyway) on the snapshots page after importing loads of templates!
=> #1185 delete template snapshots after loading

docs/internal/Element-Type-Specs.md, src/formElementPlugins/checkbox/src/ApplicationView.tsx
Check box bug fix from base updated develop.
Includes validation state message as a label.
Checked using feature showcase to test.
=> check box bug fix commited from new branch with base develop

src/utils/hooks/useGetQuestionReviewHistory.tsx, src/utils/hooks/useLoadApplication.ts, src/utils/hooks/useTriggers.tsx
=> 1264 await trigger on application restart and allowe view history when last answer is null

docs/internal/Element-Type-Specs.md, src/formElementPlugins/ApplicationViewWrapper.tsx, src/formElementPlugins/dropdownChoice/localisation/default/strings.json, src/formElementPlugins/dropdownChoice/localisation/pt_an/strings.json, src/formElementPlugins/dropdownChoice/src/ApplicationView.tsx, src/formElementPlugins/types.ts
This allows users to save new options to drop down lists.
I believe there is a more elegant solution, but this is the best I can come up with.
=> add drop down add other option

src/containers/Main/AuthenticatedWrapper.tsx
closes #1258 
Fix as per issue description
=> 1258 Fix navigation to password reset

src/utils/generated/graphql.tsx, src/utils/graphql/queries/getTemplates.query.ts, src/utils/graphql/queries/templateBuilder/getCategories.query.ts
Quick fix to try sort out the problem found in https://github.com/openmsupply/conforma-templates/issues/19
=> Change ordering of templates returned to Dashboard to orderBy code

src/containers/TemplateBuilder/shared/DropdownIO.tsx, src/containers/TemplateBuilder/template/Actions/ActionConfig.tsx, src/containers/TemplateBuilder/template/Actions/Actions.tsx, src/containers/TemplateBuilder/template/Form/ElementConfig.tsx, src/utils/generated/graphql.tsx, src/utils/graphql/queries/templateBuilder/getAllActions.query.ts
Fixes #1287
Add orderBy in actionPlugins
=> #1287 Alphabetical order of actions in Template builder

src/containers/Review/assignment/AssignmentSubmit.tsx, src/utils/generated/graphql.tsx, src/utils/hooks/useUpdateAssignment.tsx
Fixes #1303 & fixes #1195
Not sure why this was missing it. But it does fix the problems 2 and 3 described in the bug.... Problem 1 is still wip, it will require a little more work than I was imagined.
Fix for 2 problems listed related to trigger not being called when self-assignment, unassignment or re-assignment happened
=> #1303 - Part 2 - Fix assignment available for applications Reviewed or Assigned by others

src/components/List/Cells/ReviewerActionCell.tsx, src/utils/defaultLanguageStrings.ts, src/utils/generated/graphql.tsx, src/utils/hooks/useLocalisedEnums.ts
Fixes #1303 
Based on PR: #1309  
Required Back-end PR: https://github.com/openmsupply/conforma-server/pull/818
- Add new action AwaitingResponse to the ReviewAction to be displayed in the applications list
=> #1303 - Part1 - Return reviewer list action when changes required

src/components/Main/Footer.tsx, src/utils/defaultLanguageStrings.ts
=> Hard-code footer text

utils/Conforma.postman_collection.json
I did a big tidy up of this the other day, so thought it would probably be useful to keep it in the repo.
=> Postman collection

src/containers/DataDisplay/DataViewDetail.tsx, src/containers/DataDisplay/DataViewTable.tsx, src/containers/DataDisplay/DataViews.tsx, src/containers/User/UserArea.tsx, src/utils/helpers/endpoints/endpointUrlBuilder.ts, src/utils/helpers/endpoints/types.ts, src/utils/hooks/useDataViews.tsx, src/utils/types.ts
Front-end changes required to work nicely with back-end [#859 ](https://github.com/openmsupply/conforma-server/pull/859)
There's no actual functionality changes here, it's just changing variable names to be more appropriate, and the url structure to match the back-end endpoint url changes.
See [back-end PR](https://github.com/openmsupply/conforma-server/pull/859) for how to test.
=> #825F Data View front-end changes

src/config.ts, src/containers/List/ListWrapper.tsx, src/formElementPlugins/search/localisation/pt_an/strings.json, src/formElementPlugins/search/src/useDebounce.ts
Fix #1352 
See inline comment for what the problem was.
Have also added basic debouncing, but this is unrelated to the main bug
=> #1353 Fix search box

src/utils/helpers/list/findUserRole.ts
Fixes #1370 
One-line PR 
Missing new Police type in reviewer permissions map
=> #1370 - Fix applications list for ReviewAll permissions users

src/components/PageElements/PageElements.tsx, src/containers/DataDisplay/helpers.tsx, src/containers/TemplateBuilder/template/Form/ElementConfig.tsx, src/formElementPlugins/listBuilder/src/helpers.ts, src/utils/generated/graphql.tsx, src/utils/graphql/fragments/element.fragment.ts, src/utils/graphql/queries/getApplicationsList.query.ts, src/utils/helpers/structure/generateReviewerResponsesProgress.ts, src/utils/hooks/useCreateReview.tsx, src/utils/hooks/useLoadApplication.ts, src/utils/hooks/useRestartReview.ts, src/utils/types.ts
Back-end PR: https://github.com/openmsupply/conforma-server/pull/879
=> Remove usused variables from getApplicationsList

semantic/src/site/globals/site.overrides, src/components/Dashboard.tsx, src/utils/graphql/queries/getApplicationsList.query.ts, src/utils/helpers/list/buildQueryVariables.ts, src/utils/helpers/utilityFunctions.ts, src/utils/hooks/useListApplications.tsx
Replacement for closed PR https://github.com/openmsupply/conforma-web-app/pull/1387
@CarlosNZ please have a look on this one and reply to suggestions will be on original PR.
I'm having a problem with styles to display the filters now And would like some help with that if possible. Thanks!
=> #892B part2 suggestion of improvements to filters in dashboard

src/containers/Review/assignment/useGetAssignmentOptions.ts
@nmadruga this is the same as my suggestion from the other day -- please merge it into your branch if you're happy with it. It seems to be working okay for me.
=> #1408 suggestion -- add "Yourself" to top of list

src/containers/Review/ReviewPage.tsx, src/utils/generated/graphql.tsx, src/utils/graphql/queries/getReviewInfo.query.ts, src/utils/helpers/structure/generateReviewSectionActions.ts, src/utils/hooks/useGetReviewInfo.tsx, src/utils/types.ts
Front-end changes required for back-end PR https://github.com/openmsupply/conforma-server/pull/959
We'll need to double check all the cases where locking is relevant before signing off on the feature branch too.
=> 956F Review locking updates

src/utils/defaultLanguageStrings.ts
Fixes https://github.com/openmsupply/conforma-templates/issues/59
=> #59T Change string to replace List of Questions

src/containers/TemplateBuilder/shared/OperationContextHelpers.tsx
Required for back-end: https://github.com/openmsupply/conforma-server/pull/968
See notes there. (and inline comments here)
=> #967F Template category export/import fix

src/utils/helpers/list/buildQueryVariables.ts, src/utils/hooks/useListApplications.tsx
Fix #1451 
Very small tweak -- sets proper default page size from prefs (or fallback to 20).
Test -- load a list with more than 20 applications (such as registered companies in current Angola) and check that list is restricted to 20 applications.
=> #1451 List pagination fix

src/utils/hooks/useReferenceDocs.ts
Simple fix to stop showing internal menu to external users
=> #110 - Fix Other: Help & Reference list menus

src/containers/TemplateBuilder/evaluatorGui/evaluatorFunctions.ts, src/containers/TemplateBuilder/shared/Evaluation.tsx, src/utils/helpers/evaluateElements.ts
Front-end changes required for implementation of [Back-end issue](https://github.com/openmsupply/conforma-server/pull/1005)
Please note that even though I have added the `functions` param to objects in all places passing `evaluatorParameters` this is how the checkboxes still looks on the TemplateBuilder sections page
Opening the element ("Permissões") and running the evaluation for parameter `checkboxes` works correctly though. 💁
=> #1004B filter array evaluator custom function

src/formElementPlugins/ApplicationViewWrapper.tsx, src/formElementPlugins/SummaryViewWrapper.tsx, src/formElementPlugins/password/src/ApplicationView.tsx, src/formElementPlugins/search/src/ApplicationView.tsx
Quick fix for places where the evaluator functions weren't being passed to the expression evaluator.
=> Missing evaluator functions

src/config.ts, src/containers/User/UserArea.tsx
Requires back-end https://github.com/openmsupply/conforma-server/pull/1040
This just:
- Moves the "Lookup table" menu item to the "Manage" menu
- Changes the endpoint routes for lookup tables.
=> 816B Lookup table manager access control

README.md, package.json, src/containers/Dev/Snapshots.tsx, src/containers/TemplateBuilder/Templates.tsx, src/containers/TemplateBuilder/template/General/General.tsx, src/containers/TemplateBuilder/useGetTemplates.ts
Not sure if this is in the right place? I wasn't sure where else this should go
=> Update docs for npm login

semantic/src/site/globals/site.overrides
=> 1553-mobile-layout-smaller-tasks

semantic/src/site/globals/site.overrides, src/components/Application/Navigation.tsx, src/components/Application/ProgressBar.tsx, src/containers/Application/ApplicationPage.tsx, src/containers/List/ListWrapper.tsx, src/containers/User/UserArea.tsx, src/utils/defaultLanguageStrings.ts, src/utils/helpers/list/mapColumnsByRole.ts
Fix #1557 
I didn't add a "Page" selector as we already have Previous/Next buttons and it seemed to cluttered.
So have just added a "Page" indicator to the top, and a "Section" selector at the bottom:
**TOP:**
**BOTTOM:**
Have also made some small tweaks elsewhere, see inline comments for details
=> #1557 Mobile navigation in application

semantic/src/site/globals/site.overrides, src/components/Admin/AdminPreferences.tsx, src/containers/User/UserArea.tsx
Fix #1579 
Minor tweaks to the hamburger menu
=> #1579 Hamburger tweaks

semantic/src/site/globals/site.overrides, src/components/Application/ApplicationContainer.tsx, src/containers/Application/ApplicationWrapper.tsx
Fix #1587 
Plus, I fixed up the header at the top of the application page. Turns out we'd been doing something wrong the whole time -- the "organisation" that appears at the top should be the company that made the application we're looking at, not the current logged in company (that's already in the Header bar!), so have fixed that and tidied it up a little.
=> #1587 App intro page and App header fix

semantic/src/site/collections/menu.overrides, semantic/src/site/collections/message.overrides, semantic/src/site/globals/site.overrides, src/containers/Review/ReviewWrapper.tsx, src/containers/Review/assignment/AssignmentSectionRow.tsx, src/containers/Review/assignment/AssignmentTab.tsx, src/containers/Review/assignment/ReviewSectionRow.tsx, src/containers/Review/overview/Overview.tsx
Have tried to use Semantic as much as possible to do the heavy lifting.  Hopefully I haven't disturbed the desktop portion too much by using Grid columns in some places and leveraging the Stackable property of a grid.
1. Removed ProgressBar for mobile.  Fits well in simple 2 step processes, but in the more complicated it goes awry.
2. Removed Icon in the Review->Overview Tab.   Didn't seem necessary to provide in mobile
3. Tab headers wrap.  Thought about drop down as it might be cleaner looking, but tabs are easier to navigate.
4. Checked assignment tab looks ok with multiple stages.
=> 1558 review page and tabs

semantic/src/site/globals/site.overrides
Fix #1599 
This is a pretty tiny fix. I won't know for certain that it addresses the exact problem I found until I look at it in a build, but it probably does.
=> #1599 Dashboard width fix

semantic/src/site/collections/table.overrides, semantic/src/site/globals/site.overrides, src/containers/DataDisplay/ApplicationLinks.tsx, src/containers/DataDisplay/DataViewDetail.tsx, src/containers/DataDisplay/DataViewTable.tsx
Fix #1598 
Styles for Data View details page:
=> #1598 Fix Data View table view and Linked Applications

semantic/src/site/collections/table.overrides, semantic/src/site/globals/site.overrides, src/components/List/ApplicationsList.tsx, src/containers/User/UserArea.tsx, src/utils/helpers/list/mapColumnsByRole.ts
Fix #1605
Getting the "Action" button to appear in the corner was actually harder than I expected. See comments for more detail.
It would be even harder to make it a button -- I tried wrapping in a button, but, because it would contain an existing component, then:
- the styling doesn't work correctly on hover
- we'd have to define a different icon for each type of action, as a generic one wouldn't make sense, and that's adding even more complexity
- it actually doesn't look that great (IMHO)
=> #1605 Mobile application list tweak and linkable logo

docs/internal/Element-Type-Specs.md, src/formElementPlugins/listBuilder/pluginConfig.json, src/formElementPlugins/listBuilder/src/ApplicationView.tsx, src/formElementPlugins/listBuilder/src/displayComponents/ListCardLayout.tsx, src/formElementPlugins/listBuilder/src/displayComponents/ListInlineLayout.tsx, src/formElementPlugins/listBuilder/src/displayComponents/ListListLayout.tsx, src/formElementPlugins/listBuilder/src/helpers.ts, src/formElementPlugins/listBuilder/src/types.ts
2 extra parameters for listBuilder -- see docs for info
=> Data format option for listbuilder

src/components/Dashboard.tsx, src/containers/TemplateBuilder/Templates.tsx, src/containers/TemplateBuilder/shared/NumberIO.tsx, src/containers/TemplateBuilder/template/General/Categories.tsx, src/containers/TemplateBuilder/template/General/General.tsx, src/containers/TemplateBuilder/template/TemplateWrapper.tsx, src/containers/TemplateBuilder/useGetTemplates.ts, src/utils/generated/graphql.tsx, src/utils/graphql/fragments/template.fragment.ts, src/utils/graphql/queries/getTemplates.query.ts, src/utils/graphql/queries/templateBuilder/getAllTemplates.query.ts, src/utils/hooks/useListTemplates.tsx, src/utils/types.ts
=> 1545 Dashboard template priority

src/components/Admin/AdminLocalisations.tsx, src/components/Admin/Manage.tsx, src/config.ts, src/containers/User/UserArea.tsx, src/utils/helpers/endpoints/endpointUrlBuilder.ts, src/utils/helpers/endpoints/types.ts, src/utils/localisation/exportLanguages.ts, src/utils/localisation/importLanguages.ts, utils/Conforma.postman_collection.json
Front-end for https://github.com/msupply-foundation/conforma-server/pull/1096
=> #1095F Allow localisation control with systemManager permission

src/containers/Review/assignment/AssignmentSectionRow.tsx, src/containers/TemplateBuilder/template/Permissions/PermissionNameList.tsx, src/containers/TemplateBuilder/template/Permissions/PermissionReviewLevels.tsx, src/containers/TemplateBuilder/template/Permissions/Permissions.tsx, src/containers/TemplateBuilder/template/Permissions/ReviewTemplatePermission.tsx, src/utils/generated/graphql.tsx, src/utils/graphql/fragments/fullTemplate.fragment.ts, src/utils/graphql/fragments/templateStage.fragment.ts, src/utils/graphql/mutations/templateBuilder/updateTemplateStage.mutation.ts, src/utils/graphql/queries/getReviewInfo.query.ts, src/utils/hooks/useGetReviewInfo.tsx, src/utils/types.ts
=> #1628 Restrict lower level reviews to single reviewer
