- documentation/Home.md
- documentation/_Sidebar.md
- documentation/external/Home-External.md
- documentation/internal/Home.md
- utils/convert_docs_to_wiki.py
Fixes #7. 
1. Remove top-most `Home.md` file and rename `internal/Home-Internal.md` back to `internal/Home.md` (This will automatically make it the wiki "home" page.
2. Exclude `external` folder from being pushed to the wiki.
3. Create `_Sidebar.md` to represent the folder structure.
> #7 Update docs, create Sidebar

- src/elementPlugins/ApplicationViewWrapper.tsx
- src/elementPlugins/ErrorBoundary.tsx
- src/elementPlugins/JsonInput.tsx
- src/elementPlugins/TemplateViewWrapper.tsx
- src/elementPlugins/basicText/pluginConfig.json
- src/elementPlugins/basicText/src/ApplicationView.tsx
- src/elementPlugins/basicText/src/TemplateView.tsx
- src/elementPlugins/index.tsx
- src/elementPlugins/pluginProvider.tsx
- src/elementPlugins/textInfo/pluginConfig.json
- src/elementPlugins/textInfo/src/ApplicationView.tsx
- src/elementPlugins/textInfo/src/TemplateView.tsx
- src/elementPlugins/types.ts
- src/generated/graphql.tsx
To test please use this branch (https://github.com/openmsupply/application-manager-web-app/tree/%2315-Core-plugins-skeleton-front-end-EXAMPLE) and go to /pluginElement (you can change template configuration and they will reflect in the application state), also the diff for your reference: https://github.com/openmsupply/application-manager-web-app/compare/%2315-Core-plugins-skeleton-front-end...%2315-Core-plugins-skeleton-front-end-EXAMPLE
First of all I've added a rough roadmap for the rest of the work on plugins: https://github.com/openmsupply/application-manager-web-app/issues/15#issuecomment-705289839
Basically each plugin resides in a folder within `elementPlugins`, they have:
https://github.com/openmsupply/application-manager-web-app/blob/5b3c45a3d597e2b4fe99a629b682b0da24d0703c/src/e …
> #15 core plugins skeleton front end

- src/components/Application/ApplicationStart.tsx
- src/containers/Application/ApplicationCreate.tsx
- src/containers/Application/ApplicationNew.tsx
- src/containers/Application/ApplicationPage.tsx
- src/contexts/ApplicationState.tsx
- src/utils/generated/graphql.tsx
- src/utils/graphql/mutations/createApplication.mutation.ts
- src/utils/graphql/queries/getApplication.query.ts
- src/utils/hooks/useLoadTemplate.tsx
- src/utils/types.ts
Fix #27. Merging to #14 (will be merged back to master as bulk).
- Renamed type `TemplatePayload` to TemplateTypePayload`
- Created hook to do `getTemplateQuery`. It makes the query using another Apollo-client hook that returns `data`, `loading` and `error`.  The `data` returned is manipulated after its returned to get only a few properties. Then the properties, error and loading status are returned by this hook.
> #27 Hook to load template query

- src/cache.ts
- src/containers/Application/ApplicationCreate.tsx
- src/containers/Application/ApplicationPage.tsx
- src/contexts/ApplicationState.tsx
- src/index.tsx
- src/utils/generated/graphql.tsx
- src/utils/graphql/queries/getTemplate.query.ts
- src/utils/helpers/getSectionsPayload.tsx
- src/utils/hooks/useGetElementsInPage.tsx
- src/utils/hooks/useLoadApplication.tsx
- src/utils/hooks/useLoadTemplate.tsx
- src/utils/types.ts
Fixes #58.
**Important**: Run using back-end on https://github.com/openmsupply/application-manager-server/pull/83
- Change from using `goBack` for previous page to having a handler for the previous button.
- Elements to be displayed on the `ApplicationPage` are selected by index. 
- Next button logic also changed to consider:
- Each section starts from `page1`
- Go to the next section based on `section.index`
- The `useLoadTemplate` hook currently is finding the number of pages per section which is stored in the **ApplicationState**
- The `useLoadApplication` logic to find each section pages is removed.
> #58 update logic of elements order by index

- src/containers/Application/ApplicationList.tsx
- src/containers/Application/ApplicationOverview.tsx
- src/containers/Application/ApplicationPageWrapper.tsx
- src/utils/generated/graphql.tsx
- src/utils/graphql/queries/getApplication.query.ts
- src/utils/hooks/useLoadApplication.tsx
This should address #67 and #103 (and maybe #68?), although there might be more to do if I've misunderstood the issue requirements.
Please test with back-end branch `#96-more-data-for-trigger-payload` (in PR #98), as this includes a fix for the stage/status computed columns,  which you'll need to see updated statuses in the Application list.
**Changes**:
- Each application in Application List is click-able (on Title field) and goes to `/applications/{serialNo}`
- `useLoadApplication` query also returns current stage and status
- Implemented `isReady` boolean to wait for `useLoadApplication` (and skip that query subsequently) and perform some re-direct logic after application is loaded. (We discussed this way of handling waiting for initial Hooks -- hopefully it's implmented as envisaged) …
> #67 Links from Application list and Re-directs

- src/components/Application/ApplicationSummary.tsx
- src/containers/Application/ApplicationPageWrapper.tsx
- src/elementPlugins/shortText/src/ApplicationView.tsx
- src/utils/generated/graphql.tsx
- src/utils/hooks/useGetResponsesAndElementState.tsx
- src/utils/hooks/useLoadApplication.tsx
- src/utils/hooks/useTriggerProcessing.tsx
Note: Requires branch from https://github.com/openmsupply/application-manager-server/pull/102
Please `database_init` and restart server before testing.
This fixes most of the main loading/display bugs introduced during the last couple of days' merges:
- each loading hook should wait until data from previous hooks is available
- correct response object shape used throughout (incl back-end). Expects actual response value to be in `.text` field of response
- set `useLoadApplication` to use `network-and-cache` fetch policy -- this ensures that applications that have already been loaded will get their new status updated from server when re-displaying. (Important when, after submitting, you go back to the Application List and click on it -- it needs to know the status is no longer "Draft")
- …
> #114 Bug fixes 13/11

- package.json
- yarn.lock
Fix [back-end issue 116](https://github.com/orgs/openmsupply/projects/6#card-49472471) (Should have been front-end issue.)
Bump evaluator version based on [latest fixes](https://github.com/openmsupply/application-manager-server/pull/122).
Don't forget to `yarn install` to import latest version
> #116 update evaluator

- src/formElementPlugins/ApplicationViewWrapper.tsx
- src/formElementPlugins/dropdownChoice/src/ApplicationView.tsx
2 small fixes -- #153 & #155
**NOTE**: If it's not already merged, this should go with back-end PR: https://github.com/openmsupply/application-manager-server/pull/130
#153 was due to the old "0 === false" trap in javascript. Needed to change to an explicit `defaultIndex !== undefined` check, because "defaultIndex" can often be 0, which would return false. :(
#155 There's probably a more thorough fix involving making sure `validationState` is properly calculated before rendering the child plugin. However, for now, having a fall-back (`isValid: true`) options will do the trick.
> #153 #155 Bug fixes

- src/containers/Application/ApplicationPageWrapper.tsx
- src/formElementPlugins/ApplicationViewWrapper.tsx
- src/formElementPlugins/SummaryViewWrapper.tsx
- src/formElementPlugins/dropdownChoice/pluginConfig.json
- src/formElementPlugins/dropdownChoice/src/ApplicationView.tsx
- src/formElementPlugins/pluginProvider.tsx
- src/formElementPlugins/shortText/pluginConfig.json
- src/formElementPlugins/textInfo/pluginConfig.json
- src/formElementPlugins/types.ts
- src/utils/types.ts
Implements #124, specifically [this comment](https://github.com/openmsupply/application-manager-web-app/issues/124#issuecomment-736943099)
Note: please review with back-end [PR #124F](https://github.com/openmsupply/application-manager-server/pull/134) as it provides template changes to demonstrate the features here.
The only difference from the solution described in #124 is that the dynamic values are only re-evaluated on losing focus rather than on every keystroke. This can be changed if it's deemed necessary.
Have set the following fields to be dynamically evaluated:
- **textInfo**: `title, text`
- **shortText**: `label`
- **dropdownChoice**: `label, options`
After re-initialising the database with the changes in 124F, start a new "Test Register" application to see demonstration of …
> #124 Dynamic parameters in template elements

- src/containers/Main/SiteLayout.tsx
- src/utils/generated/graphql.tsx
- src/utils/graphql/fragments/response.fragment.ts
Counterpart to [back-end PR/Issue 135](https://github.com/openmsupply/application-manager-server/pull/142)
Changes in front-end:
- Removed `timeCreated` from query as it's now generated automatically by database (on creation) (solved #172)
- Added link to new Template (ReviewTest) in side-bar
> #135B Review test template

- src/containers/Application/ApplicationPageWrapper.tsx
- src/utils/generated/graphql.tsx
- src/utils/types.ts
Using back-end [PR#135](https://github.com/openmsupply/application-manager-server/pull/142)
Fixes #196 
Please, merge only after [PR#135B](https://github.com/openmsupply/application-manager-web-app/pull/195) is merged.
Simple fix to the problem of always showing one invalid page for the first page on a section - it was considering that the first page should always run a STRICT validation, since it wasn't checking for status of previous section, and always considering the previous section was visited.
PS: The second bug described on the same issue, was a configuration problem. So nothing to fix for that one.
> #196 Fix problem with invalid not-visited page

- documentation/internal/Overview-of-Navigation-&-URL-structure.md
- src/components/Application/ProgressBar.tsx
- src/components/Application/SectionSummary.tsx
- src/containers/Application/ApplicationList.tsx
- src/containers/Application/ApplicationPageWrapper.tsx
- src/containers/Application/NavigationBox.tsx
- src/containers/Main/SiteLayout.tsx
- src/containers/Review/ReviewOverview.tsx
- src/containers/Review/ReviewPageWrapper.tsx
- src/containers/Review/index.ts
- src/containers/User/UserRegister.tsx
Implements #200 -- routes and basic parameter parsing for Review pages.
Some URLs to try:
- http://localhost:3000/review/6250
- http://localhost:3000/review/6250/1234
Have added Consolidation (and Approval) routes, but just linked to `<NoMatch>` component for now.
Still working on docs, but publishing PR now so you can review it if you want.
> #200 Review routing and placeholder components

- src/containers/Application/ApplicationOverview.tsx
- src/containers/Application/ApplicationPageWrapper.tsx
- src/utils/helpers/revalidateAll.tsx
Implements #135 -- just a fairly small extension to #194 (so you'll need [that PR's back-end branch](https://github.com/openmsupply/application-manager-server/pull/150) to test against, if it's not already merged)
This PR does two additional things:
1. Ensures that any empty response (null, undefined or empty string) all get set to "invalid" (for required questions) when re-validating all (change to `revalidateAll.tsx`). This ensures that when attempting to load Summary, you'll be taken back to first incomplete page (strict check), not just page with an invalid element (loose check).
2. Loading "Draft" application re-directs user to first invalid/incomplete page (instead of section 1, page 1) -- uses the same `revalidateAll` and `firstErrorLocation` functions as #194. (This does NOT write …
> #135 Redirect application to first incomplete page

- src/components/Application/ProgressBar.tsx
- src/containers/Application/ApplicationPageWrapper.tsx
- src/containers/Application/NavigationBox.tsx
- src/utils/helpers/getPreviousPage.tsx
- src/utils/types.ts
Fix #206
- Simply check for the previous page of the **aimed** page the user wants to go. Using the same `validatePreviousPage` in both `NavigationBox` and `ProgressBar` for reusability, although it made the process a bit less clear when click **Next**. 
1. Create a new "Review Test form" application
2. Fill all elements in page 1, loose focus on last on so it will validate
3. Now click on Section 2 **Product Info**, and it will wrongly take you there!
> #206 Fix problem with validation check on progress bar

- src/components/Application/ApplicationStart.tsx
- src/components/Application/ProgressBar.tsx
- src/utils/constants.ts
- src/utils/generated/graphql.tsx
- src/utils/graphql/fragments/template.fragment.ts
- src/utils/hooks/useLoadTemplate.tsx
- src/utils/types.ts
Fix #182 
Using [Backend-#182F](https://github.com/openmsupply/application-manager-server/pull/162).
- Layout on start application page
- Fetches `startTitle` and `startMessage` for template to be displayed on start application page.
- Add every string as constant to the constants file.
- Show application page if start message is defined.
- [Existing behaviour] Create the application when 'Get started' button is pressed.
- [#232] If `startTitle` or `startMessage` not defined - go straight to start page OR last invalid (or incomplete) page.
- [#236] Show progress on start page of Draft application:
- Show progress on each section and validation icons.
- Hide 'Get started' button when application already exists.
- Show 'Resume' button on the last section with invalid (or incomplete) …
> #182 Show the start page with title and message defined for template

- package.json
- src/components/Application/ApplicationStart.tsx
- src/formElementPlugins/textInfo/src/ApplicationView.tsx
- src/utils/helpers/semanticReactMarkdown.tsx
- yarn.lock
Implements #237.
This is branched off #182, so I haven't used the module in a Submission page yet, but this should be super-easy to do in the Submission page PR using the new Markdown component.
Essentially, I've created new component called "MarkdownBlock" in `semanticReactMarkdown.tsx` which uses the [ReactMarkdown library](https://www.npmjs.com/package/react-markdown) to convert the input Markdown text to HTML, but with additional rendering over-rides which allow us to specify what kind of SemanticUI component should be returned instead of straight HTML.
The only component type I've defined so far is "Message", which is implemented on the Start page. Additional renderers can be added to semanticReactMarkdown.tsx as required. If no semantic component is specified, the module will return …
> #237 Markdown module

- src/formElementPlugins/ApplicationViewWrapper.tsx
- src/formElementPlugins/SummaryViewWrapper.tsx
- src/formElementPlugins/shortText/src/ApplicationView.tsx
- src/formElementPlugins/textInfo/src/ApplicationView.tsx
- src/formElementPlugins/types.ts
- src/utils/helpers/semanticReactMarkdown.tsx
Implements #86.
Already had Markdown display for TextInfo plugin, but I've moved the import to the Wrapper(s) and the component is passed to plugin components as a prop (as discussed).
- applied Markdown interpreter to `label` elements in Application and Summary views.
- added new 'noParagraph' renderer to Markdown module -- this prevents labels being returned wrapped in `<p></p>` tags, which messes up the label display.
> #86 Markdown for plugins

- package.json
- yarn.lock
Just upgrades the package version to allow use of the `stringSubstitution` operator.
Complement of [back-end PR #177](https://github.com/openmsupply/application-manager-server/pull/177).
Don't forget to `yarn install` to update :)
> #176F Bump evaluator version

- src/containers/Application/ApplicationPageWrapper.tsx
- src/containers/User/Login.tsx
- src/utils/generated/graphql.tsx
Implements #149. As discussed in that issue, I've left the "password plugin" to a [separate issue](#253) as there are additional complexities involved with that.
Requires [back-end PR #173](https://github.com/openmsupply/application-manager-server/pull/173) -- most of the logic changes are in there. This front-end is basically just naming/tidying of existing code.
Logging in with one of the existing users (password: "123456") should work with hash comparison on back-end.
> #149 Use password hash for login

- documentation/internal/Element-Type-Specs.md
- src/formElementPlugins/dropdownChoice/src/ApplicationView.tsx
Very small tweak to make this work. Have added documentation for the new parameter `search`.
To see it working, use back-end branch from [PR #217](https://github.com/openmsupply/application-manager-server/pull/217) -- on page 2 of the Feature Showcase application, the "API lookup" element has the searchable parameter enabled.
Thinking that this is probable enough for demonstration purposes. Rather than have a strict "lookup" element, we can just add (for example) ATC codes and their long-form string together in a list of options, and the user can easily search by either ATC code or the full name. (To be clear, I mean each option is a string containing both the ATC code and the full name, i.e. "N02AJ06 | codeine and paracetamol" )
> #325 Add search capability to Dropdown plugin

- src/containers/List/ListWrapper.tsx
- src/utils/constants.ts
- src/utils/hooks/useRouter.tsx
Implement #208.
Querying the back-end via search query in URL was already implemented, this just adds a UI search box which updates the URL as you type.
~~Had to expose a little more `useRouter` functionality to the calling component, as we need to handle conversion of the queries back into a kebab-case URL.~~
**UPDATE**: I have simplified this quite a bit in my next PR (Sorting columns #322), so this useRouter messiness will be gone. You may wish to set the base to master on #322 and just review that, since Search and Sort end up sharing quite a bit.
> #208 Search application list

- src/containers/Application/ApplicationWrapper.tsx
- src/containers/Main/SiteLayout.tsx
Fix #341
New route `application-new` to point to `ApplicationWrapper` nested route and link to new pages re-structured in [Epic#21](https://github.com/openmsupply/application-manager-web-app/issues/101). 
Added some local components to each page - to be replaced by proper ones (in new files) on next PRs.
> #314 Create application wrapper router

- src/components/Application/PageElements.tsx
- src/components/Application/index.ts
- src/containers/Application/ApplicationPage.tsx
- src/formElementPlugins/ApplicationViewWrapperNEW.tsx
- src/formElementPlugins/defaultValidate.tsx
- src/formElementPlugins/shortText/src/ApplicationView.tsx
- src/formElementPlugins/types.ts
- src/utils/constants.ts
- src/utils/hooks/useGetFullApplicationStructure.tsx
- src/utils/types.ts
Implements #348.
A PageElements component for rendering a passed-in array of elements.
I've only implemented it to work with ApplicationPage for now, as it'll be easier to add the Summary and Review displays once we have their parent pages.
But it's working nicely with Application now, and I've implemented the plug-in Wrapper level validation state checks as per @andreievg 's latest diagram. If you want to see what a page looks like with "Strict" validation, just set `isStrictPage` to `true` temporarily
The ApplicationViewWrapperNEW file is not that different from the original ApplicationViewWrapper -- just updated validation functionality. You can compare the diffs between those two files to see changes if you want.
Note: for Summary and Review, there will need to be another "Sections" …
> #348 PageElements component

- src/components/List/ApplicationsList.tsx
- src/containers/List/ListWrapper.tsx
- src/utils/generated/graphql.tsx
- src/utils/types.ts
Fixes #211 
Create expanded row on the list of Applications to be showing sections of application with Progress (To be done in #363).
- Each `ApplicationList` that represents one application on the list has also a flag `expanded` to determine if it is expanded on the list
- On the `ApplicationsList` component there is a icon on each application row to allow expansion of display the sections area.
- When expanding/collapsing the sections the table needs to get reloaded - needed to pass a new props to `ApplicationsList` to reload the table, otherwise it was not re-rendering after clicking on the expansion icon.
> #211 expand rows on applications list

- src/components/Application/ProgressBarNEW.tsx
- src/containers/Application/ApplicationPage.tsx
- src/utils/generated/graphql.tsx
- src/utils/helpers/structure/buildSectionsStructureNEW.ts
- src/utils/helpers/structure/generateProgress.ts
- src/utils/hooks/useGetFullApplicationStructure.tsx
- src/utils/types.ts
Implement #374 with re-direction on ApplicationPage.
Couple of comments:
- am calculating `firstInvalidPage` and `firstInvalidPageStrict`, but I think we really only want the "strict" value -- any re-directs are going to be based on strict, right? Let me know if you think we can remove the non-strict one
- Calulated these values during the iteration over the pages rather than a new function
- Removed the `invalidPage` field from .progress -- after discussion with Nicole, we don't really need to know the first invalid page for each section.
- Added a check on ApplicationPage -- will re-direct you if you attempt to load a page beyond your current valid one (in linear mode).
- It will work to have all buttons link to whatever page,then have this function re-direct, but it's a bit ugly. So …
> #374 firstInvalidPage handling

- src/components/Application/ProgressBarNEW.tsx
- src/containers/Application/ApplicationPage.tsx
- src/utils/generated/graphql.tsx
- src/utils/helpers/structure/checkPageIsAccessible.ts
- src/utils/helpers/structure/generateProgress.ts
- src/utils/helpers/structure/generateProgressInStructure.ts
- src/utils/hooks/useGetFullApplicationStructure.tsx
- src/utils/hooks/useLoadApplication.tsx
- src/utils/hooks/useLoadApplicationNEW.ts
- src/utils/types.ts
Fixes #351 
~~Branched of #366 please merge it first before this one!~~ DONE
- Use new `FullStructure` to display on the `ProgressBar` new component, now each Page has a progress and no longer needs to deduce the page progress on the go.
- Simplified the component (compared to old `ProgressBar`) to be easier to read, there is an alternative to using `Grid` commented, but that needs a bit tweaking to get rid of the background on `Label`...
- Change pages on **non linear** applications, ~~still has a TODO to deal with **linear** which is pending on checking with @andreievg what was the approach decided (it has been removed from Application Flow chart).~~
- [In progress] Adding validation to change to another page on **linear** applications
> #351 new progress bar component

- src/components/Application/ProgressBarNEW.tsx
- src/containers/Application/ApplicationPage.tsx
- src/contexts/FormElementUpdateTrackerState.tsx
- src/formElementPlugins/ApplicationViewWrapperNEW.tsx
- src/formElementPlugins/dropdownChoice/src/ApplicationView.tsx
- src/utils/helpers/structure/generateProgress.ts
- src/utils/hooks/useGetFullApplicationStructure.tsx
- src/utils/hooks/useLoadApplication.tsx
- src/utils/hooks/useLoadApplicationNEW.ts
- src/utils/types.ts
Branched from #351 
While reviewing #351, I've noticed a few issues:
* Is strict wasn't being applied to progress bar (i.e. when there is a strict validation fail progress bar should indicate which page and section)
* Empty field wasn't being shown as invalid in application view wrapper when it has an empty string
* When value was not change but field focused/unfocused, request validation was failing (it was hanging)
* When future page is failing strict validation but navigating to even further page from lower page, no navigation happens (i.e. I am on page 1, page 2 is invalid, i am trying to navigate to page 3)
* 
* Renamed (globally) `firstIncompletePageInSection` to `firstStrictInvalidPageInSection` <- because it could be completed but not valid
* Changes FormElementUpdateTrackerState …
> polish of validation and progress bar logic

- src/utils/helpers/structure/addEvaluatedResponsesToStructure.ts
- src/utils/hooks/useGetFullApplicationStructure.tsx
After a deeper look, it seems the functionality that needs to be shared is adding responses to structure (and evaluating them)
* Extracted logic from useGetFullApplicationStructure to addEvaluatedResponsesToStructure
* Added conditional parameter to specify what needs to be evaluated (isVisiblity, isRequired, isEditable, isValid)
Most of the evaluator logic is the same as it was, apart from `evaluateSingleElement`.
Also had to fight type script a few times (when accessing properties of an object that are not indexable by string)
> #383 extract evaluation of response from usetGetFullApplicationStructure

- src/components/Application/ApplicationHeader.tsx
- src/components/Sections/SectionsProgress.tsx
- src/components/Sections/index.ts
- src/containers/Application/ApplicationHome.tsx
- src/containers/Application/ApplicationWrapper.tsx
- src/containers/Main/AuthenticatedWrapper.tsx
- src/formElementPlugins/dropdownChoice/src/ApplicationView.tsx
Fixes #345 
~~#371~~ MERGED 
- New component `ApplicationHeader` to render the top part of the  container on Home page and **back to list** button. It also receives the content to be displayed inside its container
- New component `SectionsProgress`  to display  all sections in the application (using **fullStructure.sections** with each progress on sections and a **Resume** button on the first section with invalid/incomplete page
- Find the correct first section with invalid page to be done in issue #374 
- When all sections are complete show the **Review & Summary** button on the Home page
- When the application is not in `Draft` or `Changes Requested` status redirect to the Summary page (Issue #367 in progress)
- Add `fluid` to main container to display the application a little better on …
> #345 Application home page

- src/components/Review/ReviewSection.tsx
- src/components/Review/ReviewSubmission.tsx
- src/containers/Application/ApplicationWrapper.tsx
- src/containers/Main/SiteLayout.tsx
- src/containers/Review/ReviewOverview.tsx
- src/containers/Review/ReviewPageWrapper.tsx
- src/containers/Review/ReviewWrapper.tsx
- src/containers/Review/index.ts
Fixes #377 
- Add `ReviewWrapper` with routes to new pages to be using new structure to render in UI
- Call `ReviewWrapper` from `ApplicationWrapper` to display nested routes (temporally) using paths:
- Review Home [localhost:3000/applicationNEW/12345/review](http://localhost:3000/applicationNEW/12345/review)
- Review Page [localhost:3000/applicationNEW/12345/review/1](http://ocalhost:3000/applicationNEW/12345/review/1)
- Review Summary [localhost:3000/applicationNEW/12345/review/1/summary](http://localhost:3000/applicationNEW/12345/review/1/summary)
- Add TODOs to remove container/components when re-structure is finished
> #377 Create Review nested routes

- src/components/Application/ApplicationEdit.tsx
- src/components/Application/ApplicationStart.tsx
- src/components/Application/Navigation.tsx
- src/components/Application/ProgressBar.tsx
- src/components/Application/SectionSummary.tsx
- src/components/Application/index.ts
- src/components/index.ts
- src/containers/Application/ApplicationCreate.tsx
- src/containers/Application/ApplicationHome.tsx
- src/containers/Application/ApplicationOverview.tsx
- src/containers/Application/ApplicationPage.tsx
- src/containers/Application/ApplicationPageWrapper.tsx
- src/containers/Application/ApplicationSubmission.tsx
- src/containers/Application/ElementsBox.tsx
- src/containers/Application/NavigationBox.tsx
Fixes #350 
- ~~#375~~ MERGED
- Create new `Navigation` component to display **Previous** and **Next** button along with **Review & Summary** (to be implemented in #365) in a raised (using Sticky) component on the bottom of the current page.
- Uses `revalidateMethod` on the Next button handler to catch any problems in the current page (using the same approach from ProgressBar - that triggers a revalidation and calls the method received once it's done).
- Add TODOs on various components/containers to be destroyed once Re-structure for Applications is completed - pretty soon.
> #350 ApplicationPage with previous and next buttons

- src/components/Sections/SectionsProgress.tsx
- src/containers/Application/ApplicationHome.tsx
- src/formElementPlugins/dropdownChoice/src/ApplicationView.tsx
Fixes #318 
- ~~PR #384~~ MERGED
- ~~#375~~ MERGED 
- Add edit button on `ApplicationHome` to display on application that editable, completed and before a strict section.
- Uses the `firstStrictSectionPage` to be displayed as the section with `Resume` button when user navigates to the home page.
- `SectionsProgress` component to be used by Review and Application to display the progress on each section - and options. The **badly** named received prop `changes` to be used by Review/Edit application and allow many different labels to the button that display on the same line as a section that needs attention. Thought about instead of doing passing a constructed a UI structure to this component that only renders cells... But just did this way now so we can discuss more the idea.
> #318 Edit button on application home

- src/containers/Application/ApplicationPage.tsx
- src/containers/Application/ApplicationSubmissionNEW.tsx
- src/containers/Application/ApplicationWrapper.tsx
- src/containers/Application/index.ts
- src/utils/hooks/useLoadApplicationNEW.ts
- src/utils/types.ts
Fixes #365 
- Create new `ApplicationSubmission` page container that receives the structure and only display the page - I wasn't sure if that might be just a component - since there isn't much logic going on here. But I guess we might have later on.
- Change type **FullStructure.info** to also keep the `submissionMessage` used in the Submission page for an application
- Change type **FullStructure.stages** to be replaced with what was agreed on the new [Naming Changes Structure Diagram](https://app.diagrams.net/#G1wEk_eH1uWd8LC0JeKAM58bUkGncxKDgW). 
- Disclaimer: Although changes were done to same structure in use by old Application pages, I didn't have to change anything since the previous `stages` with `submissionMessage` was stored in a different object with type `ApplicationStages` …
> #365 New submission page

- src/contexts/FormElementUpdateTrackerState.tsx
- src/formElementPlugins/ApplicationViewWrapperNEW.tsx
Fixes #413 
@CarlosNZ noticed an issue with slow internet connection and different browser.
found that entered wasn't set properly in plugin wrapper, and found that context wasn't working (allowing changes to look like they haven't occurred and revalidation to happen straight away instead of waiting for updates)
> fix bug with revalidation

- src/containers/Review/ReviewWrapper.tsx
- src/utils/generated/graphql.tsx
- src/utils/graphql/queries/getApplication.query.ts
- src/utils/graphql/queries/getReview.query.ts
- src/utils/graphql/queries/getReviewAssignment.query.ts
- src/utils/graphql/queries/getReviewInfo.query.ts
- src/utils/graphql/queries/getReviewStatus.query.ts
- src/utils/hooks/useGetResponsesAndElementState.tsx
- src/utils/hooks/useGetReviewAssignment.tsx
- src/utils/hooks/useGetReviewInfo.tsx
- src/utils/hooks/useLoadApplication.tsx
- src/utils/hooks/useLoadApplicationNEW.ts
- src/utils/hooks/useLoadReview.tsx
- src/utils/hooks/useLoadSectionsStructure.ts
- src/utils/hooks/useRevalidateApplication.ts
- src/utils/hooks/useTriggerProcessing.tsx
- src/utils/messages.ts
- src/utils/types.ts
Fixes #378 
Use new back-end in [PR#229](https://github.com/openmsupply/application-manager-server/pull/229) to get `timeCreated` field for the current `status` in each review.
To be continue in #379 (Hopefully PR today) and display all ReviewAssignment/Reviews associated to current user in the ReviewHome page. There will be no sections displayed yet, and the reason why the `getReviewInfo` query only return the number of ReviewQuestionAssignment so far (out of curiosity).  
- Add query `getReviewInfo.query` to simply get all reviewAssignments based on current reviewer and application id
- Add hook `useGetReviewInfo` which will create the array of AssignmentDetails (new type based on existing one), with fields to display on #379 for each row of Review
- Passed on the `assignments` array to …
> #378 New hook useGetReviewInfo

- src/containers/Application/ApplicationCreateNEW.tsx
- src/containers/Application/ApplicationSubmissionNEW.tsx
- src/contexts/FormElementUpdateTrackerState.tsx
- src/utils/hooks/useLoadApplicationNEW.ts
- src/utils/hooks/useLoadTemplateNEW.tsx
Simplified version that doesn't require extra hook.
**URLs to test:**
http://localhost:3000/applicationNEW/new?type=ReviewTest (static Start message)
http://localhost:3000/applicationNEW/new?type=TestRego (dynamic Start message)
http://localhost:3000/applicationNEW/new?type=UserRegistration (should skip Start page and go to application)
(and their Submission messages at the end)
Only difference in terms of function between this version and [the other one](#419) is that this won't start rendering anything until message is evaluated. Shouldn't make much difference in practice, though, unless there was a slow API look-up or something in the expression, which is quite unlikely considering use cases.
> #418 Evaluate start and submission messages in existing Loading hooks (simplified)

- src/utils/generated/graphql.tsx
- src/utils/graphql/fragments/response.fragment.ts
- src/utils/graphql/fragments/reviewResponse.ts
- src/utils/graphql/queries/getReviewNEW.query.ts
- src/utils/helpers/structure/addEvaluatedResponsesToStructure.ts
Front-end complement to [back-end PR #234](https://github.com/openmsupply/application-manager-server/pull/234)
Just accounts for the change of field name from `timeCreated` to `timeUpdated` in the application_response and review_response tables.
> #228B Change timestamp field name for responses

- src/components/Application/Navigation.tsx
- src/components/Application/ProgressBarNEW.tsx
- src/containers/Application/ApplicationHome.tsx
- src/containers/Application/ApplicationPage.tsx
- src/containers/Application/ApplicationSubmissionNEW.tsx
- src/containers/Application/ApplicationSummary.tsx
- src/containers/Main/SiteLayout.tsx
Quick update to just replace the NEW routes with the "standard" routes, and have changed the previous "standard" to have OLD in the URL, so we can still get to them if we want.
Replaced all the links throughout that were pointing to a NEW url to now point to standard urls
No changes to file names or component names, that can be done later. This is just to make our life a bit easier in the meantime.
> Replace NEW routes

- src/utils/generated/graphql.tsx
- src/utils/graphql/queries/getApplicationsList.query.ts
- src/utils/helpers/list/buildQueryVariables.ts
- src/utils/hooks/useListApplications.tsx
- src/utils/types.ts
As per backend branch in this PR: https://github.com/openmsupply/application-manager-server/pull/266
* Fix compilations after changes to back end
* pass through review ID to application list query
* added new field to application list:
```
reviewAssignedCount
reviewAssignedNotStartedCount
reviewAvailableForSelfAssignmentCount
reviewDraftCount
reviewChangeRequestCount
reviewSubmittedCount
```
Go to application list as one of the reviewers, open dev tools and reload page. you should see a graphql query for application list and inspect it to see new field in nodes
> #227-part-1-adding-reviewer-actions-to-application-list

- src/utils/generated/graphql.tsx
- src/utils/hooks/useQuerySectionActivation.tsx
Original issue #473 seems to be already implemented. So all I've done is added a `.sort()` to `currentActiveSections` so that they always show up in a consistent order. (i.e. "=S1,S2" not "S2,S1"). Fairly trivial, but quick fix.
Note: just sorts alphabetically by Section code. Doesn't put them in true application order as that would involve passing round indexes into the hook which seems like too much trouble and not worth it.
> #473 Sort currentActiveSections

- src/formElementPlugins/dropdownChoice/src/ApplicationView.tsx
- src/formElementPlugins/radioChoice/src/ApplicationView.tsx
- src/utils/generated/graphql.tsx
Simple fix for #480. Did the same thing to Dropdown selector as well, as it works exactly the same way.
Just fixed the `useEffect` that runs on first load to always save the response if there is a default specified.
You can see it working with the "Feature Showcase" template. Page 2 has a Radio button whose selection affects the visibility of the following Dropdown. Previously, no additional dropdown appeared until a selection was made in the radio button, even though there was a default selection. Now you'll see the Dropdown appear immediately before any user interaction with the radio buttons. You can also inspect the database to see responses for Radio buttons and Dropdowns being written immediately on load, not just when selected by a user. 
If no default is specified in parameters, …
> #480 Fix default value not being saved

- src/components/Application/PageElements.tsx
- src/formElementPlugins/ApplicationViewWrapperNEW.tsx
- src/formElementPlugins/types.ts
- src/utils/helpers/structure/addApplicantChangeRequestStatusToElement.ts
Fixes #499 
- Fix problem not showing warning on Application changes required - for responses without changes required.
**Edited on 30/03**
- Bug fix to stop displaying the "This is a new submission and will require a review." warning on a new Application.
- To fix unwanted warning I removed `isChanged` and `isChangeRequired` fields getting set on `addApplicantChangeRequestStatusToElement`, so it only get set to each `state` element in the fullStructure when there is at least one review done in the full structure. This prevents a new application to display warnings - since they use the same component `PageElements` and `ApplicationViewWrapper`.
> #499 - Tiny bug fix

- src/containers/Application/ApplicationHome.tsx
- src/containers/Application/ApplicationPageWrapper.tsx
- src/containers/Review/ReviewHome.tsx
- src/containers/Review/ReviewPage.tsx
- src/containers/Review/ReviewPageWrapper.tsx
- src/containers/Review/ReviewSectionRow.tsx
- src/utils/hooks/useGetApplicationStructure.tsx
- src/utils/hooks/useGetFullReviewStructure/index.tsx
- src/utils/hooks/useGetReviewStructureForSection/helpers.tsx
- src/utils/hooks/useGetReviewStructureForSection/index.tsx
- src/utils/hooks/useGetReviewStructureForSection/useGetReviewStructureForSection.tsx
- src/utils/hooks/useGetReviewStructureForSection/useGetReviewStructureForSectionAsync.tsx
- src/utils/hooks/useRestartReview.ts
- src/utils/types.ts
Fixes #396 
#568 - Remove old router and files used for Application
Renamed `hook` and files/folder (from-to):
- useGetFullReviewStructure => useGetReviewStructureForSection
- useGetFullApplicationStructure => UseGetApplicationStructure
- Should I also rename the type `FullStructure` to `Structure` or leave it as it is?
> #396 Rename hooks to get FullStructure

- semantic/src/site/globals/site.overrides
- src/containers/User/UserArea.tsx
- src/utils/generated/graphql.tsx
- src/utils/helpers/utilityFunctions.ts
- src/utils/types.ts
Implements #580 
Please use back-end branch `#583-final-tidyups-for-create-join-org`
Note, I've also merged front-end `#583-final-tidy-ups-for-create-join-org'`, so there's currently a few little changes showing in the diff that don't belong in this issue -- the only files I've changed here are:
- UserArea.tsx
- utiltityFunctions.ts
To get logos for existing orgs into the database, please use this snapshot, and these files:
[581_logos.graphql.zip](https://github.com/openmsupply/application-manager-web-app/files/6339747/581_logos.graphql.zip) - snapshot 
[files-#580.zip](https://github.com/openmsupply/application-manager-web-app/files/6322123/files-.580.zip) - files folder
Then you should see logos for 3 of the 4 available orgs in the Header.
Note that one of them (Drug Dealers West) has …
> #580 Show company logo in Header

- src/containers/List/ListWrapper.tsx
- src/utils/generated/graphql.tsx
- src/utils/helpers/list/checkExistingUserRole.ts
- src/utils/helpers/list/findUserRole.ts
Fixes #620 
- Quick fix to remove 2 problems:
1. When entering an invalid userRole on the URL (it will replace with first existing for current user)
2. When entering a userRole that the current user doesn't have permission (also replaces with first one user has permission)
- Changed the order of userRoles to always show list based on `applicant` user when user can act as applicant or reviewer.
- We don't display on the UI how to swap between different user, but you can enter another (valid) userRole to see the list from another perspective.
> #620 Fix bug user role based on user

- package.json
- yarn.lock
Just published package @expression-evaluator with new version 1.6.2
Please also check back-end [PR](https://github.com/openmsupply/application-manager-server/pull/325) for bumping @expression-evaluator.
> #317B Part 2 - Bump to version 1.6.2

- src/utils/data/reviewStatus.ts
- src/utils/helpers/list/findUserRole.ts
- src/utils/helpers/structure/generateReviewProgress.ts
Required for back end [back end pr](https://github.com/openmsupply/application-manager-server/pull/337)
Permission policies returned by getUser API are now in correct graphQL matching format
> change permission checking in application list to use alligned types

- semantic/src/site/globals/site.overrides
- semantic/src/site/globals/site.variables
- src/components/List/Cells/StatusCell.tsx
- src/components/PageElements/PageElements.tsx
- src/formElementPlugins/ApplicationViewWrapper.tsx
Updates the change request styles to match the latest layout and style changes. Should look pretty much the same as before (with the coloured borders around the elements).
@nmadruga -- I have tried to preserve the conditional logic for the colour/style display in ApplicationViewWrapper using simple class switching rather than inline styles, but it'd be worth having a careful look at that bit to make sure.
- Also updated the "Make Changes" style in Applications List.
**NOTE:** There is still some work to do to make these elements on the Summary page consistent with on the Review page (re-using styles, and maybe even components)
> #662(2) Change Request styles

- semantic/src/site/globals/site.overrides
- src/components/PageElements/PageElements.tsx
- src/containers/Application/ApplicationPage.tsx
- src/utils/generated/graphql.tsx
- src/utils/graphql/fragments/element.fragment.ts
- src/utils/hooks/useLoadApplication.ts
- src/utils/types.ts
Implements #645, using "Option 1" from [this discussion](https://github.com/openmsupply/application-manager-web-app/issues/681#issue-878183541)
Requires branch from [back-end PR #389](https://github.com/openmsupply/application-manager-server/pull/339)
Note that the help text can quite happily hang below the level of the next question, which means that template builders will have to mindful not to overlap them, or else this happens:
Have added more "demonstration" help text to the Feature Showcase template, but I've also added some more "realistic" help tips to some of the other templates (see back-end changes)
> #645 Implement help text tips

- src/containers/Review/ReviewSectionRow.tsx
Fixes #654 
Very basic changes, perhaps can be improved. I wasn't sure why `isReviewable` is set to true when the review isn't in **Draft**. Anyway, just a quick previous of the changes in this PR. Please test more cases - although to test Consolidation one it would better to first merge in PR #695.
I have test using this application:
Before the user self-assign it show other possible self-assigners:
After the review is assigned to one and locked to the other is doesn't show to others:
But the review is visible from your review home page (logged as Consolidator 2):
And other reviews which are already submitted would show as well. I think that was the idea.
> #654 Show your assignment rows and review progress rows

- src/containers/Application/ApplicationHome.tsx
- src/containers/Application/ApplicationWrapper.tsx
- src/utils/hooks/useLoadApplication.ts
- src/utils/types.ts
Fixes #638.
An unevaluated "startMessage" was being passed to ApplicationHome. Have fixed so that both startMessage and submissionMessage are evaluated in `useLoadApplication` and stored in structure.info (previously it was just submissionMessage), so evaluated startMessage string can be available in ApplicationHome.
To test: start a new application. You should see a correctly rendered "Start Message" box on both the "ApplicationCreate" page `/new?...` and the "ApplicationHome" page (`/application/<serial>`).
> #638 Fix Application Home start message

- src/utils/generated/graphql.tsx
- src/utils/helpers/list/buildQueryFilters.ts
- Add new filters for `assigner` and `reviewer` filtering. 
- Problem is that we don't set the `assigner_id` yet, so can't test that. 
- To test with `reviewer` I was using:
Go to see the list of `ReviewTest` applications
- Test 1: Filter by "testReviewer1" with URL `http://localhost:3000/applications?type=ReviewTest&user-role=consolidator&reviewer=testReviewer1` who is assigned to all applications, so nothing changes.
- Test 2: Filter by "testReviewer2" with URL`http://localhost:3000/applications?type=ReviewTest&user-role=consolidator&reviewer=testReviewer2` now only 3 applications will show because this user isn't assigned to one of the applications
> #310B New filters by reviewer and assigner

- utils/convert_docs_to_wiki.py
- utils/push_docs_to_wiki.sh
As mentioned in Telegram chat:
> Noticed that the images for the documentation weren’t showing up in front end wiki. Turns out images must be in the format `[[relative/path/to/images | alt-text]]` format and doens’t work (needs path from root) in the `!(alt-text)[image/path]]`, which is what we’d been using. Good news is we can do without the python conversion script, but will need to go through and replace images links with the other Markdown syntax. (Better than having to specify full paths)
> But I still think we need a small script to copy to the “_wiki” folder for publishing. That way we can keep a copy in the main repo and review documentation changes along with PRs, and then “publish” them once approved. If we edit them directly int he submodule folder (/_wiki) then we won’t see …
> Publish to wiki fixes

- documentation/internal/Element-Type-Specs.md
- src/formElementPlugins/checkbox/src/ApplicationView.tsx
- src/formElementPlugins/radioChoice/src/ApplicationView.tsx
- src/formElementPlugins/shortText/src/ApplicationView.tsx
Fixes #750 #751
Requires back-end branch `#750F-radio-buttons-inline` ([PR #382](https://github.com/openmsupply/application-manager-server/pull/382)) -- have only implemented for elements that are part of the Ingredients list (Section 3, page 2, FeatureShowcase) -- to bring UI closer to the designs for the Ingredients list
- Add "layout: inline" parameter to radioChoice and implement custom style based on this selection
- Add "maxWidth" parameter to shortText and implement custom style based on this value
- Since this solution is more elegant than what was used in "Checkbox" element, I've updated checkbox to match this pattern, too.
> #750 #751 Radio button and shortText updates

- documentation/internal/Element-Type-Specs.md
- package.json
- src/containers/Application/ApplicationCreate.tsx
- src/containers/Outcomes/OutcomesDetail.tsx
- src/formElementPlugins/ApplicationViewWrapper.tsx
- src/formElementPlugins/listBuilder/src/ApplicationView.tsx
- src/formElementPlugins/longText/src/ApplicationView.tsx
- src/formElementPlugins/shortText/src/ApplicationView.tsx
- src/utils/generated/graphql.tsx
- src/utils/graphql/fragments/element.fragment.ts
- src/utils/helpers/evaluateElements.ts
- src/utils/helpers/structure/addEvaluatedResponsesToStructure.ts
- src/utils/hooks/useCreateApplication.tsx
- src/utils/hooks/useGetApplicationStructure.tsx
- src/utils/hooks/useLoadApplication.ts
- src/utils/hooks/useLoadTemplate.tsx
- src/utils/types.ts
Fixes: #761 
Requires back end branch in this PR: https://github.com/openmsupply/application-manager-server/pull/395
Wanted to delegate default value work to generic functionality, for it not to be plugin specific. This is needed to pre-fill default values for plugins like listBuilder.
note: Kept dropbox and radio button default parameter, however defaultValue on element will take priority
* There is back end change to add defaultValue to element, please refer to back end PR
* Juggled types a little bit, and made useLoadApplication to be more strongly typed (previous 'as' cast ignored missing or miss typed field
* Simplified evaluation logic of element and made it usable in other context
* Create application now evaluates default values and inserts evaluated defaults on application …
> #761 generic default value handling to work for all plugins

- src/contexts/FormElementUpdateTrackerState.tsx
- src/formElementPlugins/ApplicationViewWrapper.tsx
Fixes: #717 
will make an issue tomorrow for this:
replication
* create org rego
* fill the fist page
* go to second page
* go back to first page
* try to go to next page
made validation a little bit more resilient (didn't realise plugins would be changing values, even if it's not change, and on subsequent loads)
> make sure validation doesn't break when plugin saves the same value

- semantic/src/site/collections/table.overrides
- semantic/src/site/globals/site.overrides
- src/LookupTable/hooks/useGetAllTableStructures.hook.tsx
- src/LookupTable/hooks/useGetSingleTable.hook.tsx
- src/LookupTable/hooks/useGetSingleTableStructure.hook.tsx
- src/components/PageElements/PageElements.tsx
- src/containers/Outcomes/ApplicationLinks.tsx
- src/containers/Outcomes/Outcomes.tsx
- src/containers/Outcomes/OutcomesDetail.tsx
- src/containers/Outcomes/OutcomesList.tsx
- src/containers/Outcomes/OutcomesTable.tsx
- src/containers/Review/AssignmentSectionRow.tsx
- src/containers/User/UserArea.tsx
- src/formElementPlugins/SummaryViewWrapper.tsx
- src/formElementPlugins/listBuilder/src/SummaryView.tsx
- src/index.tsx
- src/utils/hooks/useGetApplicationStructure.tsx
- src/utils/hooks/useLoadTemplate.tsx
- src/utils/hooks/useSubmitApplication.tsx
Small bits added to demo server:
* Spacing between tables cells (for outcome table to not be squashing things
* Add label to list build summary view
* Show summary view if template category is information
* use network only and remove cache persist for graphQL queries (saw cache errors when loading/reloading snapshots, need investigation)
* silently ignore errors in outcomes
* link in top menu to outcomes and lookup tables
> Demo extras

- semantic/src/site/globals/site.overrides
- src/components/PageElements/Elements/ConsolidateReviewDecision.tsx
- src/components/PageElements/Elements/ReviewApplicantResponse.tsx
- src/components/PageElements/Elements/ReviewResponseElement.tsx
Fixes #787
based on PR #788 
As described in the issue, there are 3 cases to update with latest designs (using Option 2):
Although keep in mind that we are limiting to show only 3 maximum of response-elements (anything that was submitted by one of the applicant's reviewer or the applicant himself). Soon we will have the "Show history" option to list anything else more than the latest 3. : )
Have tried to only change things strict related to this, with help from @CarlosNZ was able to not need to change existing less files so much - only added the `blue-border` around what needs to be in context with inline-decision and that's it.
We agreed that we won't have a duplicate text version of the Applicant's response, so using straight Applicant response:
After re-review should show exactly as …
> #787 Update inline decision with designs (option 2)

- src/formElementPlugins/fileUpload/src/ApplicationView.tsx
Fixes #777 
In the `useEffect` watching the "uploadedFiles" array, we now check if the length is 0, in which case we (re)set the saved response to `null`.
> #777 Fix for empty file upload responses

- src/formElementPlugins/SummaryViewWrapper.tsx
Fixes #818 
Very simple fix -- the SummaryViewWrapper useEffect was not watching the "allResponses" object like the ApplicationViewWrapper was.
It didn't used to matter for the Summary page, as the parameters never changed after loading, but now that we're displaying SummaryView in application forms (for INFORMATION types), the parameters can change in response to other responses.
> #818 Parameters not updating in Summary View

- src/components/PageElements/Elements/ConsolidateReviewDecision.tsx
- src/components/PageElements/Elements/ReviewApplicantResponse.tsx
- src/components/PageElements/Elements/ReviewInlineInput.tsx
- src/components/PageElements/PageElements.tsx
- src/components/Review/HistoryPanel.tsx
- src/components/Sections/SectionWrapper.tsx
- src/containers/Application/ApplicationPage.tsx
- src/containers/Application/ApplicationSummary.tsx
- src/containers/Review/ReviewPage.tsx
- src/formElementPlugins/ApplicationViewWrapper.tsx
- src/formElementPlugins/textInfo/src/ApplicationView.tsx
- src/formElementPlugins/textInfo/src/SummaryView.tsx
- src/utils/constants.ts
- src/utils/generated/graphql.tsx
- src/utils/graphql/fragments/applicationResponse.fragment.ts
- src/utils/graphql/fragments/reviewResponse.fragment.ts
- src/utils/graphql/mutations/updateResponse.mutation.ts
- src/utils/graphql/mutations/updateReviewResponse.mutation.ts
- src/utils/graphql/queries/getHistoryForApplicant.query.ts
- src/utils/graphql/queries/getHistoryForReviewer.query.ts
- src/utils/hooks/useGetQuestionReviewHistory.tsx
- src/utils/hooks/useUpdateReviewResponse.ts
Fixes #811 
- [Back-end#811F](https://github.com/openmsupply/application-manager-server/pull/435)
- Show Stage label on top of each block of elements in History Panel
- Update each `application_response` with respective application stage_number at the time it is updated - now each application_response stored the `stage_number` so this can be used when sorting responses per stage
- Change `useGetQuestionReviewHistory` to keep object with elements per stage ordered from latest to oldest to return to HistoryPanel that will only to the rendering of stage labels and respective elements (application_responses, review_responses). 
Refer to how to test described in PR #803
> #811 show stages on history panel

- src/formElementPlugins/search/src/ApplicationView.tsx
Quick fix for the problem @nmadruga describes [here](https://github.com/openmsupply/application-manager-server/pull/451#issue-687480490)
Have added `currentUser`, `applicationData` and `responses` as part of "objects" in the search query evaluation.
> Search plugin fix - use currentUser and applicationData for search query evaluation

- src/utils/generated/graphql.tsx
- src/utils/hooks/useRestartReview.ts
Fixes #804 
The investigation took a long time, to find this. But it seemed to be a very easy fix, so this one-line PR.
- When restart a review not only check if `shouldCreateConsolidationReviewResponse` (maybe we need to change this method name, since this is also used for reviewer) and `isAssigned` and `!isActiveReviewResponse` <- for existing consolidation to not duplicate DRAFT reviewResponses on going, it now also check for `!!response` so don't create review for application question NOT entered (and probably not required).
- Create one application and review (screening or just one-level review), it needs to have one question (non-required) empty before submitting - this was the case that was causing a problem.
- When reviewing, leave at least one empty review, and approve one and …
> #804 fix review for non reviewable responses after LOQ

- semantic/src/site/elements/label.overrides
- semantic/src/site/globals/site.overrides
- src/components/Dashboard.tsx
- src/utils/constants.ts
- src/utils/generated/graphql.tsx
- src/utils/graphql/fragments/template.fragment.ts
- src/utils/hooks/useListTemplates.tsx
- src/utils/types.ts
Fixes #824 
Fixes #830 
- Back-end https://github.com/openmsupply/application-manager-server/pull/437
- Dashboard layout
- One category per row, although templates on the same category (now with fixed width) show in the same row or wrap depending on the size of page
- Update on filters to remove icons, show in grey and number after title (now pluralised on back-end)
- Title for each template also has a new `plural` field that is used to display in the Dashboard and links to "View all" applications in the list
> #824 Dashboard layout, pluralisation and remove icons in filters

- src/containers/Application/ApplicationCreate.tsx
- src/utils/generated/graphql.tsx
- src/utils/graphql/mutations/createApplication.mutation.ts
- src/utils/graphql/queries/getApplicationSerial.query.ts
- src/utils/hooks/useCreateApplication.tsx
- src/utils/hooks/useLoadApplication.ts
Fixes #840.
Requires back-end branch from [PR #454 (Generate Serials)](https://github.com/openmsupply/application-manager-server/pull/454)
- the "create" method (in useCreateApplication) returns the id of the newly created application to the "handleCreate" method in "ApplicationCreate", which sets the "id" in "ApplicationState"
- "onCompleted" removed from call to "useCreateApplication"
- a new query hook "useGetApplicationSerialQuery" added to ApplicationCreate, but it's set to `skip` when there is no id set in ApplicationState
- the new hook's "onCompleted" method is set to check the trigger of the new application. The query re-runs (with pollInterval) every half second until the trigger is reset (null), or it times out (10 attempts, just like useLoadApplication).
- when trigger === …
> #840 Wait for back-end serial generation

- semantic/src/site/globals/site.overrides
- src/components/Review/HistoryPanel.tsx
Fixes #857 (and #825).
The "first-child" top-border was necessary for response-container, but not regular Summary element, so ensured it only gets applied to response-container by using "first-of-type" selector.
Couple of additional tweaks I did here:
- Improve spacing of Stage labels on History Panel:
- Hide inner (grey) border when "blue-border" is active:
> #857 Fix weird top-border on Summary elements

- src/containers/Application/ApplicationCreate.tsx
Fixes #855 
Turns out to be a very small fix, and seems to be behaving itself now. 🤞
I'm still mystified as to what caused this -- I'm sure it was working fine when I did the original PR last week. *Something* is causing the component to reload and re-run the useEffect, even when `template` is unchanging between renders. 🤷‍♂️
> #855 Fix ApplicationCreate bug

- src/components/PageElements/PageElements.tsx
No linked issues.
Quick fix - for another quick fix (not well done - by me)
Before the application submitted was showing the **Edit** icon on all elements - allowing you to change responses after the application was submitted. So, now that's fixed.
> Fix to stop edit option showing for submitted application - when not updating

- semantic/src/site/globals/site.overrides
- src/components/Application/Navigation.tsx
- src/containers/Application/ApplicationPage.tsx
- src/containers/Application/ApplicationPageWrapper.tsx
- src/contexts/FormElementUpdateTrackerState.tsx
- src/formElementPlugins/ApplicationViewWrapper.tsx
- src/utils/constants.ts
- src/utils/types.ts
Fixes: #866 
Ended up changing element tracker to track changes for individual elements, and only supplying `latestChangedElementUpdateTimestamp` to ApplicationPageWrapper and in turn to useGetApplicationStructure as minRefetchTimestampForRevalidation.
Also introduced `sequence` to tracked elements, to make sure overlapping exit event in password plugin doesn't undermine enter event it overlaps.
Basic flow is as follows:
Each element can indicate when it's 'entered' via `setIsActive` function prop, ApplicationViewWrapper (AVW) will call setUpdateTracker `setElementEntered` with that element code. Then when element is saved AVW will call setUpdateTracker with `setElementUpdated` with that code. Entered and exited (including start and end value) events for all element are tracked, and if …
> #866 improve revalidation element state tracking

- src/containers/List/ListFilters/ListFilters.tsx
- src/containers/List/ListFilters/common.tsx
Fixes: https://github.com/openmsupply/application-manager-web-app/issues/874
Bug origin: https://github.com/openmsupply/application-manager-web-app/issues/874#issuecomment-887983407
Added `staticList` to ListFilters switch clause
> #874 add static list to list filter switch clause

- src/utils/hooks/useGetReviewStructureForSection/helpers.tsx
Fixes #846 
- When `reviewResponse` is DRAFT and not different to previous ReviewResponse, then it doesn't show on the history.
- Also simplify a little how it's checking when to show "View history" clickable label
> #846 Fix problem with draft reviews not changed showing on history

- src/containers/User/Login.tsx
- src/containers/User/UserArea.tsx
- src/utils/constants.ts
- src/utils/types.ts
Fixes #911 
Requires [back-end PR #524](https://github.com/openmsupply/application-manager-server/pull/524)
This is kind of an interim solution, we can come up with something else later on if it's a problem. For now, the FDA org never see the "No Org" selection, which is what Craig wants.
- Also tweaked the logic on the login screen, so if a user only has one org (i.e. most people), they'll skip the org selection and automatically be logged in as their only org (so won't see the "No Org" option initially). So only people who go poking around in the Org dropdown will see the "No Org" option
To test, just set the "isSystemOrg" flag on any org to "true" and note that users who are part of this org can no longer see the "No Org" option
Edit: improved it further so there is not even a Dropdown …
> #911 What is your emergency?

- src/components/PageElements/PageElements.tsx
- src/components/Review/HistoryPanel.tsx
- src/utils/generated/graphql.tsx
- src/utils/graphql/fragments/fullTemplate.fragment.ts
- src/utils/graphql/fragments/template.fragment.ts
- src/utils/graphql/mutations/createApplication.mutation.ts
- src/utils/graphql/queries/getApplication.query.ts
- src/utils/graphql/queries/getHistoryForApplicant.query.ts
- src/utils/graphql/queries/getHistoryForReviewer.query.ts
- src/utils/graphql/queries/getTemplate.query.ts
- src/utils/graphql/queries/getTemplates.query.ts
- src/utils/hooks/useGetQuestionReviewHistory.tsx
- src/utils/hooks/useListTemplates.tsx
- src/utils/hooks/useLoadTemplate.tsx
- src/utils/types.ts
Changes:
- Receives `template.version` in **templateFragment**
- Renamed fragment from Template to templateFragment (a few extra files changes because of that)
- Passes the whole object with `TemplateDetails` to the component `HistoryPanel` that will extract:
- templateCode
- templateVersion
What was missing to do (and it was a TODO in the code) was to be passing the correct templateVersion in the query.
> Fix history with proper template version

- src/formElementPlugins/dropdownChoice/src/ApplicationView.tsx
- src/formElementPlugins/radioChoice/src/ApplicationView.tsx
Fixes #784 and fixes #813 
- Based in #820 
Just adding some error-handling to radio-button to show something is wrong (using validationMessage) when trying to submit with one selected. As mentioned in "Demo server templates/configs": Radio selection on Page 3 (and maybe other radios) need a validation message to show when trying to navigate to next page without one selected - Adam's feedback
TODO:
- Add something similar to List-builder once decided
> Add error-handling for radioChoice and fix dropdown error color

- src/components/Review/ReviewSectionRowAction.tsx
- src/containers/Review/AssignmentSectionRow.tsx
- src/containers/Review/ReviewHome.tsx
- src/containers/Review/ReviewSectionRow.tsx
- src/utils/data/assignmentOptions.ts
- src/utils/hooks/useUpdateReviewAssignment.tsx
- src/utils/types.ts
1 - fixes #692  auto-assign sections to same assigner selected in one row
2 - No issue - [from Demo server config doc](https://docs.google.com/document/d/19CYbrFv2NyV69ggqWRVmbAxktPIwyNRe0W9c9xUikHM/edit#heading=h.wp1x7v9odz8) "Getting an error when trying to submit consolidation -- says “Not all sections have been reviewed” even when they are. Is this a bug?"
Fix self-assignment of consolidation not considering reviews not existing when generating questionAssignments.
The problem was related to questions with different configurations, the code logic to give reviewQuestionAssignments was different to the one from `useGetReviewStructureForSection/helpers` and therefor was considering questions with empty responses/review when generating the reviewAssignment for consolidator on …
> #692 Auto-assign sections to same assignee + Fix problem with review self-assignment for consolidation

- src/containers/Outcomes/ApplicationLinks.tsx
- src/containers/Outcomes/contexts/helpers.ts
- src/containers/Outcomes/contexts/outcomesState.tsx
- src/utils/types.ts
Fixes: #959 
Fixes: #958 
Column title was easy, just made sure it mapped properly.
As for application link, issue was in confirming that table existed, the tried to simplify logic, still not 100% happy with it.
Basically the schema query, is using snake case for tables names, so as a query parameter table name should be singular and snake. useGetSchemaColumns then converts all table names to camel case, and then in OutcomeDisplayInner we check if the table exists (now singular but in camel case). 
* Changed `getDBApplicationJoinLinkTableName` to `getApplicationJoinLinkTableName` with extra case parameter
* Use `getApplicationJoinLinkTableName` correctly to provide variable to graphql query (`useGetSchemaColumns`) and to deduce if table name exists in schema (`OutcomeDisplayInner`)
> outcome column header and application list to show correctly

- src/formElementPlugins/search/src/ApplicationView.tsx
Fixes #947 
Just updates the default "text" value saved in the response. Previously was just using `JSON.stringify()`, but the output might change as the retrieved response would change the order of the fields in the selection objects.
Added a custom string processor (when "textFormat" is not defined) -- bonus is that the output string is _slightly_ nicer to look at.
> #947 search plugin showing changes when it hasn't

- src/containers/Outcomes/contexts/helpers.ts
Partial fix for issue https://github.com/openmsupply/application-manager-server/issues/559
Not a fully fix, but it at least stops from breaking the app in case there is no applicationJoin returned, or the one returned is null for some reason. We will need to work a little more to get this outcomes page is better shape when working in https://github.com/openmsupply/application-manager-server/issues/556
> Quick fix - only prevents app from crashing

- src/containers/TemplateBuilder/template/Permissions/PermissionNameList.tsx
- src/containers/TemplateBuilder/template/Permissions/ReviewTemplatePermission.tsx
- src/utils/generated/graphql.tsx
- src/utils/graphql/fragments/fullTemplate.fragment.ts
Partial fix issue https://github.com/openmsupply/application-manager-server/issues/506
- Visible in Permisisons: on each level of a stage
- Rules: Can only be associated to level 1 review and for stage higher than 1.
- Required to get ProdRegistration template working - last stage should be final decision
- set true when selected
> Show field "Can Make Decision" in template builder UI

- src/containers/TemplateBuilder/template/General/MessagesConfig.tsx
Another partial fix for https://github.com/openmsupply/application-manager-server/issues/506
- Based on PR #948 
Just enforce starMessage to `null` in case it is set to empty string
> Fix start message as null when empty string

- src/components/Application/ApplicationHomeWrapper.tsx
- src/formElementPlugins/number/src/ApplicationView.tsx
Fix #964 
Quick little fix. Turns out clicking the stepper was only triggering the "onChange" event (which doesn't save), not the "onBlur" event (which does). Added additional "onClick" listener which calls the same function as "onBlur", so we can save input from the stepper alone.
(Also -- fixed the annoying React error about incorrectly nested DOM elements which has been low-key bugging me for ages)
> #964 Number input fix

- src/containers/Outcomes/ApplicationLinks.tsx
- src/containers/Outcomes/OutcomesTable.tsx
- src/containers/Outcomes/helpers.tsx
- src/containers/User/UserArea.tsx
- src/utils/generated/graphql.tsx
- src/utils/helpers/semanticReactMarkdown.tsx
- src/utils/helpers/utilityFunctions.ts
- src/utils/hooks/useOutcomes.tsx
Adds functionality to handle arrays returned from outomes API. Turns it into a Markdown list, and interprets each item in array in the same way as a single item.
Also uses the same "Substitution" method as used in listBuilder and generateText to populate strings with returned data.
Together this allows drill-down functionality in Outcomes, e.g. Orgs show a click-able list of member users, and vice versa.
Please continue to use back-end https://github.com/openmsupply/application-manager-server/pull/573, and the "outcomes-demo" snapshot in the "#outcomes-demo" branch of templates repo.
Example:
https://user-images.githubusercontent.com/5456533/133909714-c3f2ab31-da53-4c8f-a66c-697f44bd7b9c.mov
> #976(3) Outcome display improvements -- drill-down/list handling

- src/containers/Outcomes/helpers.tsx
Little thing I noticed while writing docs for outcome configuration.
I had changed the back-end to return "dataType" field with types more consistent with JS basic types, but missed a couple of entries in front-end that use this value.
> Quick fix -- outcomes dataTypes

- src/formElementPlugins/number/src/ApplicationView.tsx
Fix #964 (again)
Sorry, was a little hasty with yesterday's fix, the "onClick" handler was running validation checks even before any text was entered (the handler is supposed to be just for onLoseFocus, so shouldn't have happened).
Anyway, added tiny extra check to not going any further if the response is still NULL (so it behaves like the other text input plugins again)
> #964 Number plugin fix (2)

- src/components/Review/ReviewLabel.tsx
- src/components/Review/ReviewSectionRowAssigned.tsx
- src/utils/defaultLanguageStrings.ts
- src/utils/helpers/structure/generateFinalDecisionProgress.ts
- src/utils/helpers/structure/generateReviewSectionActions.ts
- src/utils/helpers/structure/generateReviewerResponsesProgress.ts
- src/utils/helpers/structure/index.ts
- src/utils/hooks/useGetDecisionOptions.ts
- src/utils/hooks/useGetReviewStructureForSection/helpers.tsx
- src/utils/types.ts
Fixes #1017 
- basically, the Final decision was only considering previous stages as Consolidation. Changes here are to also consider if only Review was done in the previous stage. I'll add the snapshot used to test in our private repo for testing
- Also fixed how the progress show and how you are able to submit now when previous stage was Review
- The idea is that previous review (or Consolidation) review responses are duplicated (after clicking on Make Decision) and the Final decision maker doesn't need to go trough each element to submit. They can just make the final decision. But are also allowed to change the existing reviewResponses (associated to them) to something else if they whish. 
- Different from other decisions the "Final decision" also can pick either **Non conform** or …
> #1017 fix final decision after review stages

- src/components/PageElements/Elements/ApplicantElementWrapper.tsx
- src/components/PageElements/PageElements.tsx
Fixes #1015
Quick fix to allow adding new responses from Application summary page in first submission
Now on first submission you can click to add a new responses -> clicking will take applicant back to page to incude response:
When updating from changes-requested option to add doesn't show to keep existing logic:
> #1015 Summary to allow applicant adding new responses

- src/containers/TemplateBuilder/shared/Evaluation.tsx
- src/containers/TemplateBuilder/shared/Parameters.tsx
- src/containers/TemplateBuilder/template/Actions/ActionConfig.tsx
- src/containers/TemplateBuilder/template/Actions/Actions.tsx
Fix #1007 
Requires back-end https://github.com/openmsupply/application-manager-server/pull/608 in order to fetch server-side applicationData for Actions
This is pretty rudimentary, but it gives us the thing that was most needed for TemplateBuilder -- seeing the result of evaluator queries in Actions editor. In particular, we can check the values going to "modifyRecord" are what we expect in the editor rather than having to test the whole template.
> #1007 applicationData for Action evaluation previews

- src/formElementPlugins/fileUpload/src/SummaryView.tsx
I missed one when updating all the urls to use new API paths. Summary view for file Upload wasn't displaying the file images correctly.
This fixes that.
> Quick fix: File upload summary view

- src/containers/Dev/Snapshots.tsx
- src/containers/TemplateBuilder/Templates.tsx
- src/containers/TemplateBuilder/shared/OperationContextHelpers.tsx
Fixes #1034 
~~There's one part not quite working still --- download/export. That's because it currently relies on a plan HTML `<a>` link so can't pass JWT into it. Will hopefully get this sorted soon, before we merge this. Have asked @andreievg for suggestion.~~ Should be good now!
Also fixes the "import template" issue (not "MULTIPART" file on server).
> #1034 Missing JWT in snapshot/template export/import queries

- docs/internal/admin/Template-Builder.md
- src/containers/Review/ReviewSubmit.tsx
- src/containers/TemplateBuilder/template/General/General.tsx
- src/containers/TemplateBuilder/template/TemplateWrapper.tsx
- src/utils/generated/graphql.tsx
- src/utils/graphql/fragments/template.fragment.ts
- src/utils/hooks/useGetDecisionOptions.ts
- src/utils/hooks/useLoadApplication.ts
- src/utils/types.ts
Fixes #1029 
- Backend https://github.com/openmsupply/application-manager-server/pull/621
- Check for new template field `isInteracive` (which by default is **true**) to display the option "List of Questions" in Review submission. 
- If the field is **false** the option to submit a LOQ is not displayed anymore. That is specifically to be used in the new UserRegistration build on private snapshot demo_laos, to not allow interaction with user who isn't registered yet.
- Display the new option in the TemplateBuilder page as well -> Add a line to docs.
- Load core_templates snapshot by running `yarn database_init` with no arguments
- Now you have to create another user to have the permission to review OrgJoin applications:
- Go ahead and register a new user "Reviewer", using your email …
> #1029 add field is interactive to template

- docs/internal/admin/Template-Builder.md
Small note/reminder regarding how to prevent [#620](https://github.com/openmsupply/application-manager-server/issues/620), as requested.
> #620B Note about proper Markdown links in email notifications

- src/containers/Application/ApplicationPage.tsx
- src/containers/Application/ApplicationSubmission.tsx
- src/formElementPlugins/ApplicationViewWrapper.tsx
- src/utils/hooks/useLoadApplication.ts
Fix #884 
Had to make "ApplicationSubmission" page fetch the full structure so it can use responses from application in submission message.
Also done here:
-- in ApplicationViewWrapper, fetch JWT from local storage on demand, as it's not always there on load when coming from non-logged in state (which causes problems with some subsequent API calls)
Suggest testing this with new "add internal user" template so you can see the effect on the Submission page ("CreateIntUser-1.zip" in `/demo_angola/templates` in templates repo)
> #884 Evaluate submission message after submission

- docs/internal/Element-Type-Specs.md
- src/containers/TemplateBuilder/shared/Evaluation.tsx
- src/containers/TemplateBuilder/template/Form/ElementConfig.tsx
- src/formElementPlugins/checkbox/localisation/default/strings.json
- src/formElementPlugins/checkbox/src/ApplicationView.tsx
Fix #1052 
~~Just quickly putting this in Draft PR so @nmadruga can begin using it, still need to thoroughly test it and tweak it.~~
One other little addition -- if the API returns more fields that the required ones, then these will also be passed along and saved with the response. For example, when fetching permission names, values like "id" will be captured and stored with the response even though they're not required for display.
Extra: fixed one more JWT error in `Evaluation.tsx` -- same issue as yesterday's fix, this is just one more I found.
> #1052 Checkbox updates

- src/formElementPlugins/checkbox/src/ApplicationView.tsx
Fix #1058 
This was a bit trickier than I originally thought it would be, as I had to figure out a way for the plugin to know whether the change was a "proper" change, or just the initial loading values. In the former case, the state should be replaced by the new values, but in the latter case (initial load), the checkbox state should be loaded from the saved response. And it's complicated by the fact that we also want to ignore the "Loading" values and not consider them a proper "change".
Anyway, the good thing is I think I can probably apply this technique to other plugins, which might make what I was trying to achieve with proper "default" values somewhat easier. We'll see.
To test (using Nicole's grant permissions template):
- on initial load, all permissions should show unchecked
- …
> #1058 Handle changing checkbox input parameters correctly

- src/components/Admin.tsx
- src/containers/Main/SiteLayout.tsx
Fix #1054 
Quick fix for this, since it's been annoying me for a few weeks now. The 404 component shouldn't show when userState is still loading, so this just checks for that before the "isAdmin" check.
> #1054 Quick fix: Admin loading problem fix

- src/formElementPlugins/SummaryViewWrapper.tsx
- src/formElementPlugins/password/src/ApplicationView.tsx
- src/formElementPlugins/search/src/ApplicationView.tsx
- src/utils/helpers/evaluateElements.ts
This should fix the problem Jess was having with the Change Password. Weird that it wasn't happening in Firefox, but just to be safe I've moved all the JWT fetches from local storage that I could find into function, so it's refetched every time rather than loaded once for each module.
> Quick fix for JWT problem

- docs/internal/Element-Type-Specs.md
- src/formElementPlugins/checkbox/src/ApplicationView.tsx
- src/formElementPlugins/checkbox/src/SummaryView.tsx
- src/utils/types.ts
Fix #1061 
Gives us more flexibility as to how we can display checkbox selections (for example, permission lists in "Grant Permissions" notification email), and also presents a nicer display in standard "SummaryView".
To see the effect in SummaryView, please load snapshot `/dev/snapshots/[TEMP]checkbox_improvements` and look at the "Feature Showcase" template -- Section 1, Page 4. Or you can just look at the way the permissions are displayed in the new permission checkbox templates (in email and verification message).
Specs described in updated docs
> #1061 Checkbox presentation improvements

- src/containers/TemplateBuilder/template/Actions/ActionConfig.tsx
- src/containers/TemplateBuilder/template/Form/ElementConfig.tsx
- src/containers/User/UserArea.tsx
- src/utils/defaultLanguageStrings.ts
Just a little thing I discovered after already building last night -- the tool-tip message for the "Save" button when disable was not appropriate for this context.
Now shows a different message depending on whether it's disabled due to not being in draft, or because no changes have been made yet.
Edit: Also quickly chucked in a link to "Snapshots" in the Admin menu, but only for dev mode -- I got sick of typing it 😜
> Fix "disabled" message on Save button

- semantic/src/site/globals/site.overrides
Oops -- something we neglected previously (I thought we'd already done it). The Dashboard needs to have a max-width so it doesn't show more than three template columns across, otherwise it looks really bad:
Noticed when adding admin permissions.
> Max width on dashboard container

- src/containers/TemplateBuilder/template/Form/Elements.tsx
- src/containers/TemplateBuilder/template/Form/Form.tsx
- src/containers/TemplateBuilder/template/Form/Sections.tsx
We missed this the other day -- when the "Form" tab loads, it opens with Section 1, Page 1, however when selecting a new Section, there was no page elements shown again.
Fix for that -- now when selecting new section the first page of that section is loaded.
> Template builder -- show page 1 by default

- src/utils/graphql/mutations/updateReview.mutation.ts
Very small change, something that was causing a small problem developing the "activity_log" for back-end. The "comment" field for "review_decision" was being written in a separate mutation, not in the review submission mutation. This just includes the comment in the main mutation as well, just in case the comment mutation hasn't finished before the submission one (which is what was causing the issue)
> Review decision -- include comment in submit

- package.json
- src/config.ts
Front-end complement of back-end PR https://github.com/openmsupply/application-manager-server/pull/657
All is does it reset the version back to 0.1.0 and use the value from "package.json" as the source of truth for version number throughout the app.
Note:
- back-end script will be responsible for updating the version numbers for both back and front end
- following semantic versioning, "pre-release" version numbers are in the format "0.1.0-1", "0.1.0-2" etc. -- these get auto-generated using `yarn version ...` (in back-end PR)
> #642B Reset version

- src/components/PageElements/PageElements.tsx
Fix #1005 
Super-quick fix. Just make the "Help" text box conditional on element visibility. This explanation is longer than the code itself ;)
> #1005 Help text fix

- src/components/List/Cells/LastActiveDateCell.tsx
Fix #1074 
The organisation column has already been done elsewhere, so all I've done is make the text for the date strings a bit smaller so it can fit on one line.
> #1074 List text adjustment

- src/components/Review/ReviewSectionRowAction.tsx
- src/containers/Review/ReviewPage.tsx
- src/containers/Review/assignment/AssigneeLabel.tsx
- src/containers/Review/assignment/AssignmentRows.tsx
- src/containers/Review/assignment/AssignmentSectionRow.tsx
- src/containers/Review/assignment/ReviewSectionRow.tsx
- src/containers/Review/assignment/useGetAssignmentOptions.ts
- src/utils/helpers/structure/generateConsolidatorResponsesProgress.ts
- src/utils/helpers/structure/generateReviewerResponsesProgress.ts
- src/utils/hooks/useCreateReview.tsx
- src/utils/hooks/useRemakePreviousReview.ts
- src/utils/hooks/useRestartReview.ts
- src/utils/types.ts
Fixes #1110 and some bugs introduced during #1115 refactor.
- Stop showing the option to re-assign for already submtited reviews
- Fix ReviewPage not rendering
- Fix assigned consolidator to be showing in all sections
- Fix start button stopped working 😬 
- Fix start button not showing for reviewer
- Fix start button not showing for consolidator
~~- Start button not creating the review~~
- Requires a full refresh on the page after swapping users - we should check if still required
- When there is a partial review done, login as the other review (that hasn't started) will show the other sections as **Not Assigned** and the option to assign (if they have permission). This is not a huge one and I'm happy to add as a new issue.
UPDATED: 18/02 -- This PR should be fixing many bugs that were …
> 1110 fix bugs related to assignment consolidation

- semantic/src/site/elements/header.overrides
- semantic/src/site/globals/site.overrides
- src/components/Review/ReviewSectionRowAction.tsx
- src/components/Review/ReviewSectionRowAssigned.tsx
- src/components/Review/ReviewSectionRowLastActionDate.tsx
- src/components/Review/ReviewSectionRowProgress.tsx
- src/containers/Review/assignment/AssignmentRows.tsx
- src/containers/Review/assignment/AssignmentSectionRow.tsx
- src/containers/Review/assignment/ReviewSectionRow.tsx
I'm not super happy with this, but there's just too many combinations of assignment rows and review rows with so many different possible things inside them, that it's too hard to make them *all* look good.
Right-justifying the actions at the end of each type of row is not possible without overhauling the whole layout structure which would be a big job.
I think this will have to do for now.
> #1115B Layout tweaks

- docs/internal/Element-Type-Specs.md
- src/formElementPlugins/longText/pluginConfig.json
- src/formElementPlugins/longText/src/ApplicationView.tsx
- src/formElementPlugins/shortText/src/ApplicationView.tsx
Fix #1032 
Restored the "default" field of shortText and longText elements, so templates have the option to use this parameter, or the shared "defaultValue" parameter -- since they behave quite differently. I've added an explanation in the docs as to what the difference is.
I have a made a snapshot: `/dev/snapshots/text_field_demo` in the templates repo. There is a template type called "Short Text Demo", which is accessible from the User menu dropdown. You can play around with the values and see the behaviour of the fields with dynamic defaults (Can log in as "Carl" and start a new form if you want)
Expected behaviour:
- Fields with dynamic defaults should change as their source values (other fields) change
- Once the user has edited the value, it will no longer change in response to …
> #1032 Restore text element default

- package.json
- src/containers/Review/ReviewWrapper.tsx
Oops -- can't believe we didn't notice this regression for so long. Looks like it slipped in when I was building the Tab structure. Send the smaller structure instead of fullStructure into the ReviewWrapper.
Luckily Adam picked it up this afternoon before tomorrow's demo:
Fortunately a really small fix.
@nmadruga I will do a new build tonight using this branch and update the demo. So you can review this PR in your own good time in case there's any other related things that I might have missed.
> Urgent Fix -- missing responses on review pages

- src/containers/Review/ReviewPage.tsx
Fixes #1122
Very small bug, caused by using the mutation instead of our Hook - where we pass the especific field required to update the original review response review_response.is_visible_to_applicant in `action_update_review_visibility`.
The bug only happened during MassApprove, when clicking on the "Agree with all" button on the consolidation.
> #1122 Fix bug with Consolidation not correctly setting LOQ to applicant

- package.json
- src/containers/TemplateBuilder/evaluatorGui/EvaluationFallback.tsx
- src/containers/TemplateBuilder/evaluatorGui/EvaluationOutputType.tsx
- src/containers/TemplateBuilder/evaluatorGui/guiDefinitions.tsx
- src/containers/TemplateBuilder/evaluatorGui/renderEvaluation.tsx
- src/containers/TemplateBuilder/evaluatorGui/semanticComponentLibrary.tsx
- src/containers/TemplateBuilder/evaluatorGui/typeHelpers.ts
- src/containers/TemplateBuilder/evaluatorGui/types.ts
- src/containers/TemplateBuilder/shared/Evaluation.tsx
- yarn.lock
Front-end complement to [back end PR #672](https://github.com/openmsupply/application-manager-server/pull/672)
Adds UI element to enable and define the Fallback for every evaluator instance.
Don't love the UI, but it's just re-using existing elements, so significant improvements not really do-able without a larger overhaul.
Make sure you `yarn install` to get the latest version of evaluator in this branch.
Note: nothing actually changed in `Evaluation.tsx`, seems like auto-formatting changes.
> UI change for evaluator fallback parameter

- src/containers/Application/ApplicationSummary.tsx
- src/formElementPlugins/fileUpload/src/ApplicationView.tsx
Fix #1143 (kinda)
Hmm, after all that time spent trying to deal with this, it looks like we can get away with a very simple fix. 🙄
This is still a bit hacky, as it's causing more re-renders than it should (as the "Submit" mutation is also causing a refresh of the structure), but at least it works as far as I can tell.
There is a back-end branch called `__delayed_actions` which you can use to test this against -- it puts a delay between each action so the trigger will be processing for a significant amount of time, therefore any "trigger waiting" errors will become apparent.
Have a think about whether this is a good enough solution to #1143, or whether we should leave that open to deal with more thoroughly at a later date.
> #1143 Trigger waiting bug

- semantic/src/site/collections/message.overrides
- semantic/src/site/collections/message.variables
- src/containers/Review/notes/NotesTab.tsx
Quick fix for the Message box regression I mentioned in [this comment](https://github.com/openmsupply/application-manager-web-app/issues/1134#issuecomment-1094380419)
(If we want the bigger shadow effect, we can still do it by adding "floating" prop to Message component)
> #Message Info box fix

- package.json
- src/LookupTable/components/DownloadButton.tsx
- src/LookupTable/components/ImportCsvModal.tsx
- src/LookupTable/components/list/ListTable.tsx
- src/LookupTable/components/single/LookUpMainMenu.tsx
- src/LookupTable/contexts/LookUpTableImportCsvContext.tsx
- src/LookupTable/hooks/useGetSingleTableStructure.hook.tsx
- src/containers/Outcomes/helpers.tsx
Fix #1033 (mostly)
Requires back-end branch from [PR #719](https://github.com/openmsupply/application-manager-server/pull/719)
Addresses all the items listed in #1033, except:
>  Should interpret non-text fields as correct type (e.g. boolean or number)
Need to be a bit careful with that. Even though I've already written a function to detect the Postgres type based on the content, I noticed some lookup tables had a mix of types (code for example is sometimes a number and sometimes text), so if we assumed that the first row was representative of the whole column, we'd cause problems. So will need to leave that for now until we can think it through a bit better, but it's not high priority for now.
The main importing error is fixed in the back-end.
I'll annotate my code with some comments to …
> #1033 #1151 Lookup table fixes/improvements

- semantic/src/site/globals/site.overrides
Tiny fix, hope it's good for other things that were also showing on top of UserArea...
Example of previous bug:
> Fix User Area to be on top of other ui

- src/components/Sections/SectionProgress.tsx
- src/utils/helpers/structure/generateConsolidationValidity.ts
- src/utils/helpers/structure/generateConsolidatorResponsesProgress.ts
Have tested with a few different scenarios and seems good - would be great to also try with review that has Make final decision checked. Tested Consolidation with:
- Standard Review - with questions not answered by applicant -> Consolidation: can self-assign, start and submit
- After sending changes to lower level reviewer -> Consolidation can re-start and submit
- After sending LOQ to applicant -> Review approves (with new questions answered in section) -> Consolidation can start and submit
> # Fix consolidation 2

- src/containers/TemplateBuilder/template/ApplicationWrapper.tsx
Fix back-end issue [#733](https://github.com/openmsupply/application-manager-server/issues/733)
Classic mistake this one -- referring to one array from another using indexes to keep them aligned, except one has been filtered and one hasn't, so the indexes no longer correspond! 😆
So now I'm just filtering the `elementsDefaults` array the same as the corresponding `templateResponses` so their indexes correspond correctly.
Only applies to "is_config" applications, not real applications, as they get created through different functions.
Bad news is it's NOT related to #1126 as I suspected -- that one will require a bit more to sort it out as there's a bit to consider.
> 733B Fix for incorrect default responses in config application

- src/formElementPlugins/checkbox/src/ApplicationView.tsx
- src/formElementPlugins/checkbox/src/SummaryView.tsx
- src/formElementPlugins/datePicker/src/ApplicationView.tsx
- src/formElementPlugins/dropdownChoice/src/ApplicationView.tsx
- src/formElementPlugins/fileUpload/src/ApplicationView.tsx
- src/formElementPlugins/fileUpload/src/SummaryView.tsx
- src/formElementPlugins/listBuilder/src/ApplicationView.tsx
- src/formElementPlugins/listBuilder/src/SummaryView.tsx
- src/formElementPlugins/longText/src/ApplicationView.tsx
- src/formElementPlugins/number/src/ApplicationView.tsx
- src/formElementPlugins/password/src/ApplicationView.tsx
- src/formElementPlugins/radioChoice/src/ApplicationView.tsx
- src/formElementPlugins/search/src/ApplicationView.tsx
- src/formElementPlugins/shortText/src/ApplicationView.tsx
In a few places, we've used an empty `label` parameter to make a form element more tightly linked with the one above it.
Unfortunately, it currently looks bad if the unlabelled element is also "required", as the small red asterisk is displayed:
This small change just makes sure the whole "label" html element for each plugin is only rendered if the label parameter is defined, so that the "required" indicator won't show up if the label doesn't, like so:
Another example with file upload connected to a previous checkbox element:
> Don't show "required" indicator if label is not defined

- docs/internal/Element-Type-Specs.md
- src/formElementPlugins/number/src/ApplicationView.tsx
It was annoying me how I could press the stepper and have negative values for the shelf life inputs in Project Reg. Was about to edit the template to set `minValue: 0`, but then realised it would just be better to have `0` as the default minimum for number input. Configuration can set a lower minimum in the rare cases we want to allow negative input.
Tiny change (and update to docs)
> Small tweak -- more sensible default minimum for number input element

- src/containers/Review/assignment/AssignmentRows.tsx
- src/containers/Review/assignment/AssignmentSectionRow.tsx
- src/containers/Review/assignment/AssignmentSubmit.tsx
- src/containers/Review/assignment/AssignmentTab.tsx
- src/containers/Review/assignment/Reassignment.tsx
- src/utils/hooks/useUpdateAssignment.tsx
- src/utils/types.ts
closes #1175 
Created new type `AssignedSectionsByLevel` which is `SectionAssignee` grouped by levels, this type is used in assignment logic.
Noticed a couple of things: 
* Should assigned level 1 be able to assign level above one ?
* Looks like we can approve consolidation when approving just one section (if other sections are not submitted by another reviewer yet)
* Review assignment of level one, that are not assigned, but when level one is fully assigned, are still AVAILABLE ? Is that ok ?
> 1175 Update assignment logic to take level into account

- docs/internal/Element-Type-Specs.md
- src/formElementPlugins/fileUpload/src/ApplicationView.tsx
This is part of a request of Adam's. The "subfolder" can already be specified in the `/upload` endpoint -- this just makes it available to the front-end plugin.
It should rarely be needed, but it will be useful for configurations when we are trying to specify where certain files should go via the UI, such as carbone templates.
> Subfolder parameter for fileUpload

- src/containers/TemplateBuilder/evaluatorGui/guiDefinitions.tsx
Fix #1187 
Now shows appropriate UI for the `objectFunctions` operator:
> #1187 Fix objectFunctions UI in template builder

- docs/internal/Element-Type-Specs.md
- src/formElementPlugins/ApplicationViewWrapper.tsx
- src/formElementPlugins/dropdownChoice/localisation/default/strings.json
- src/formElementPlugins/dropdownChoice/localisation/pt_an/strings.json
- src/formElementPlugins/dropdownChoice/src/ApplicationView.tsx
- src/formElementPlugins/types.ts
@fergie-nz -- this is branched from your one so you can compare it against what you already had.
See inline comments for more info.
Was a bit trickier than I initially thought. Basic functionality not too bad, the hard part was getting it to recognise and display a custom option when loading, when the options list isn't immediately available -- e.g. from an API.
Here's an alt version of the feature showcase to test against: [Demo-FeatureShowcase_NEW.zip](https://github.com/openmsupply/conforma-web-app/files/9237502/Demo-FeatureShowcase_NEW.zip)
In particular -- check out the drop-down at the top of page 5, where it displays a list of names from public API. Now you can add your own custom option and it will still persist even when reloading the page and waiting for the options list. …
> #1242 Drop-down custom option tweak

- src/utils/helpers/endpoints/endpointUrlBuilder.ts
- src/utils/hooks/useLoadApplication.ts
Have manually re-constructed the "config" object in applicationData, so it provides "serverREST" prop and "serverGraphQL" prop as before.
> Quick fix for faulty applicationData.config

- package.json
- src/components/Review/DecisionPreview/ReviewPreviewModal.tsx
- src/containers/Main/AuthenticatedWrapper.tsx
- src/containers/User/NonRegisteredLogin.tsx
- src/utils/helpers/endpoints/types.ts
- yarn.lock
Fix #1278
Yikes, this was a bit gnarly. @andreievg I'd be interested to see what you think and if there's a better way to go about it.
Basically, the problem with the solution you made a couple of weeks ago is that, if `state` is not present at the beginning, then even though you accounted for the case, your solution relied on "location" changing and forcing a re-render of the `AuthenticatedWrapper` component. Unfortunately, this doesn't happen, and so it just sits there perpetually re-loading.
Seems like whatever bug/issue is causing the "location" object to be missing "state", and "query" on load is also not notifying React of a change when it *is* available.
So I went with a blunt solution -- ignore React Router completely and DIY it with my own function to manually parse …
> #1278 Password reset fix (again!)

- src/containers/Main/AuthenticatedWrapper.tsx
- src/containers/User/NonRegisteredLogin.tsx
Hmmm, prompted by @andreievg 's comment [here](https://github.com/openmsupply/conforma-web-app/pull/1280/files#r944026127), I looked into this a little bit more. Our custom `useRouter` hook is already using the suggested "queryString" to fetch the url queries, and it seems that "query" is actually available when clicking through, even when "state" is missing.
I now think that the thing that was wrong was not actually the missing "sessionId", but was due to the fact that there was an `isLoggedIn()` check on load of the "NonRegisteredLogin" component, and if you were already logged in as "nonRegistered" (which you would be after filling in a password reset request) then you'd get re-directed away back to the login screen.
I think the missing "state"  / "sesssionId" was actually a bit of a …
> #1278 Password reset fix again again!

- docs/internal/Element-Type-Specs.md
- semantic/src/site/globals/site.variables
- src/formElementPlugins/checkbox/src/ApplicationView.tsx
- src/formElementPlugins/checkbox/src/SummaryView.tsx
- src/formElementPlugins/fileUpload/src/SummaryView.tsx
- src/utils/types.ts
Fix #1298 
Changed the name of the "textDisplay" parameter to "displayFormat", and added additional "checkboxes" option to display checkboxes on the Summary page.
Currently the "List" option is the default, which I've left so as to not affect existing templates, but I'm open to changing if we think it's worth it (discuss at next meeting?)
**Update**: Also addressed #1297 a11cbe49
> #1298 Checkbox improvements

- src/components/List/Cells/DeadlineCell.tsx
- src/containers/Review/overview/Overview.tsx
Fix #1300 
Now only shows date on "List" and (review) "Overview" page.
~~Still needs back-end PR to change scheduled check.~~ Should be changed in `preferences.json` now.
(If you want a quick way to test -- use the snapshot `appDeadlineTest_2022_07_16` in templates repo, submit application as "jane_smith" and request changes (as Basic Reviewer))
> 1300 Don't display time with deadline

- src/config.ts
- src/contexts/UserState.tsx
- src/utils/helpers/fetchUserInfo.ts
Fix #1291 
It was getting the correct `isManage` pref when already logged in, but when logging in, it would run the `else` part of the `onLogin` method (in UserState), which was setting `isManager` to `false`. I think I assumed it would get updated by a subsequent `fetchUserInfo` call, but it doesn't.
So this just fixes that.
> #1291 Fix "Manage" menu bar item

- docs/internal/Element-Type-Specs.md
- src/formElementPlugins/number/src/ApplicationView.tsx
Fix #1316 
Thanks for the suggestions @fergie-nz and @nmadruga, I think this is a much better use of the units suffix now.
To see in action, use latest snapshot: "angola_2022_08_26_1459" -- the 3 shelf-life fields (Mod1, pg3) have been updated to use this to display the "month" units more effectively:
Have updated the docs with correct parameters. See inline comments for further explanation.
> #1316 Number input improvements

- src/containers/DataDisplay/helpers.tsx
- src/formElementPlugins/fileUpload/src/SummaryView.tsx
Quick fix for the missing logo issue in the Company Data View.
The applicationData that was being passed to the "SummaryView" components in Data Views was incorrect due to a recent change to how the server urls are generated. I'd updated all the other applicationData's, but somehow missed this one.
Have also updated the comment to make it clearer what's going on here.
> Add correct config info to applicationData

- src/formElementPlugins/checkbox/src/SummaryView.tsx
@nmadruga this fixes the problem you were having with checkbox display. Made the SummaryView display the CheckboxDisplay component regardless, and just pass in a "dummy" empty response if no response exists.
> Quick fix: Display checkbox summary even when no response

- src/containers/Review/assignment/AssignAll.tsx
- src/containers/Review/assignment/AssignmentTab.tsx
Fix #1324 
This handles when the "allowedSections" array is empty -- as that actually means "allow all".
I actually don't really like this, I would much prefer if the "generateReviewAssignements" action put a full list of sections in when we want to allow all, but I think the ramifications of changing that right now could get messy and be hard to test thoroughly.
So this will have to do for now.
> #1324 Assign all fix

- src/utils/hooks/useGetQuestionReviewHistory.tsx
Fix #946 
I think this is all it needs. There was existing code that caught responses with no stageNumber defined, and set `stageNumber = 0`. The problem was, the *current* review response (i.e. the one just created for this new review) doesn't have a stage number yet, so we can just exclude these ones and get the correct history display.
I don't actually like how the new review responses don't get a stageNumber set until the review is responded to -- it should really be included in the "createReview" mutation. But it provides a convenient way for us to detect which review responses to exclude from the history list, so I guess we can live with it.
@nmadruga -- do you know why we don't set a stageNumber initially? Is it just an oversight, or was there a good reason for it?
> #946 Don't show invalid review responses in history panel

- src/utils/hooks/useSubmitApplication.tsx
Fix #1302.
Good we caught this now, would have been annoying to track down after release.
Turns out the "application submit" mutation had too big a payload (JSON variable) for Postgraphile. I've increased the body size limit in the back-end ([PR#836](https://github.com/openmsupply/conforma-server/pull/836)), and I've also stopped sending the "value" field of application responses when submitting application. Some of the responses have very large `value` objects (esp listBuilder), and responses should all be updated when they are edited.
I think this is safe -- please let me know if you can think of a reason why it might not be?
> #1302 Intermittent problem submitting Product Registration

- src/components/PageElements/Elements/ConsolidateReviewDecision.tsx
- src/components/PageElements/Elements/ReviewApplicantResponse.tsx
- src/components/PageElements/PageElements.tsx
- src/containers/Review/ReviewPage.tsx
- src/utils/defaultLanguageStrings.ts
Fixes #1214 
Back-end PR: [837](https://github.com/openmsupply/conforma-server/pull/837)
Tests: Please use snapshot `dev/snapshots/Unassignment_warning_test` for testing this. It won't work currently in out angola snapshot since the actions on event ON_REVIEW_ASSIGN and ON_REVIEW_UNASSIGN are not correctly set/missing.
Once you load the `Unassignment_warning_test` snapshot please run `yarn migrate` to get changes on the back-end working.
Then test: 
1. load as `jess` and see the Review of http://localhost:3000/application/S-OSW-0002/review?tab=assignment
2. Open the review page, make changes if desired - but don't submit
3. Open an incognito browser and log in as `nicole` then in http://localhost:3000/application/S-OSW-0002/review?tab=assignment do Un-assignment of jess. 
4. In the other …
> #1214 - Warning on Discontinued reviews (Unassigned)

- src/formElementPlugins/dropdownChoice/src/ApplicationView.tsx
This will prevent the problem that occurred due to misconfigured dropDown.
There was an "optionsDisplayProperty" specified, but it wasn't needed as the options query was already returning an array of strings, not an array of objects (as is required for optionsDisplayProperty to work). So it was trying to index a property of a string for its saved text, which resulted in `undefined` (therefore saving `null` to response value).
This change just checks the type of the options value and only tries to find the `optionsDisplayProperty` if it's an object. Otherwise the `optionsDisplayProperty` is quietly ignored.
> Small fix: Text fallback if optionsDisplayProperty is invalid

- src/containers/TemplateBuilder/shared/OperationContextHelpers.tsx
Fix [back-end #848](https://github.com/openmsupply/conforma-server/issues/849) Part 2:
> 2\. when _duplicating_ a template, delete the "snapshot" after import so it doesn't appear in the list (we currently do this from the front-end when _importing_ a template, but needs to happen for duplication too)
Part 1 PR [here](https://github.com/openmsupply/conforma-server/pull/850)
> #849F Delete template "snapshot" after duplicate

- src/formElementPlugins/listBuilder/src/displayComponents/ListCardLayout.tsx
- src/formElementPlugins/listBuilder/src/displayComponents/ListInlineLayout.tsx
- src/formElementPlugins/listBuilder/src/displayComponents/ListListLayout.tsx
- src/formElementPlugins/listBuilder/src/helpers.ts
- src/formElementPlugins/search/src/ApplicationView.tsx
Fix #1346 
Removes the plugin-specific "substituteValues" functions and replaces them with the generic one from utils. It does exactly the same thing, except the generic one is recursive, so it can handle nested object paths.
Noticed this when I wanted the `displayFormat` value to include `genericNames.text`, but it wouldn't work cos it didn't drill down through the object path.
Generic one does the trick (and should have been done a while ago).
Required for the "displayFormat" of the Product card in "Cancel Product" to display correctly.
> #1346 Update substituteValues in plugins

- src/containers/TemplateBuilder/evaluatorGui/evaluatorFunctions.ts
Added in Conforma-templates issues list since was made for country-specific requirement:
Fixes https://github.com/openmsupply/conforma-templates/issues/31
Back-end PR: https://github.com/openmsupply/conforma-server/pull/858
🔝 Basically same changes - required to get the Action working (Preview & Sending email)
Testing: Please load snapshot (on Conforma-templates repo): `dev/snapshots/Formatted_dates_in_email`
Use user `jess` to preview emails for decision: "Non Conform" or "List of Questions" for review in progress.
Use user `nicole` to preview email for decision "Conform"
Details:
- Check this using Preview of "Non conform" as configured in the SendEmail action:
- Check this using Preview of "List of Questions" and config in the SendEmail action:
- Check this using Preview of "Conform" …
> #31T - Adding new optional locale to getFormattedDate function

- src/components/PageElements/Elements/ReviewApplicantResponse.tsx
- src/containers/Review/ReviewPage.tsx
Fixes #1351 
We already have the logic in place to only consider elements reviewed that are in assigned sections to determinate the overall decision. So, the only change required was to hide the option to edit elements that aren't part of the assigned sections...
1. The reviewer `Nicole Madruga` had all sections assigned, and started to review Section 1:
2. Now review `Nicole Madruga` has been un-assigned from Section 1:
PS: The user can still see their previous reviews, not sure if I should hide this too...
Reviewer can submit after finishing the assigned work (previous logic)
> #1351 - Hide option to edit/add reviews on elements in re-assigned sections

- src/components/List/Cells/DeadlineCell.tsx
- src/containers/Review/notes/NotesTab.tsx
- src/contexts/Localisation.tsx
- src/formElementPlugins/datePicker/src/ApplicationView.tsx
- src/utils/defaultLanguageStrings.ts
- src/utils/hooks/useTimeline/eventInterpretation.ts
- src/utils/hooks/useTimeline/useTimeline.tsx
- src/utils/localisation/exportLanguages.ts
- src/utils/localisation/importLanguages.ts
Just add locale to our localisation file and use in Notes tab (Review) and Applicant Deadline
Notes tab example (using locale: 'pt'):
Considering... do we need to change this as well?
> Tweak for dates in correct format (using Locale from localisation file)

- src/containers/List/ListFilters/ListFilters.tsx
- src/utils/helpers/list/useGetFilterDefinitions.ts
Fix #1361 
The problem was, when going to the page from the dashboard, the "defaultDisplayFilters" was empty, because the `userRole` had not yet been defined from the query, but we initialised `activeFilters` with this anyway. 
And then when the query updated, the active filters got over-written with `[...activeFilters, ...newFilters]`, which was also empty. And even though`defaultDisplayFilters` was updated, the state of `activeFilters` didn't change, since it was only the initialised value that depended on it.
This change just moves consideration of `defaultDisplayFilters` into the `useEffect` that happens when the query changes -- and if there are no filters already active or defined in the query, it'll use the default ones.
This also means that if you load a page with a filter already …
> #1361 Application list -- default filters fix

- src/formElementPlugins/search/src/SummaryView.tsx
Fix #1365.
Not sure how long this has been like this, maybe forever? 🤷‍♂️
Anyway, I've just put the same Form and Label wrapper in the Summary View so it's consistent with all the other Summary View components.
> #1365 Fix missing label on Search Summary view

- semantic/src/site/globals/site.overrides
- src/components/Application/ApplicationContainer.tsx
- src/utils/defaultLanguageStrings.ts
Just 2 tweaks on the Application Home page.
1. Changed the string, which wasn't easy to translate in Portuguese
2. Re-ordered the Title (with Company name) and back button
* It has annoyed me for a while. I tried a few things, and re-ordering so the company shows first and the button to see Applications list after seems a little bit better.
> Tweaks in application container

- src/containers/Application/ApplicationSummary.tsx
- src/utils/hooks/useGetApplicationStructure.tsx
Fix #1232 
Finally got to the bottom of this one. 
If you haven't seen the problem, I'm pretty sure you can re-create it by looking at a completed application as the applicant.
The problem was the application progress was being recalculated, even for completed applications, which was causing the validity check to fail on the summary page, and redirect back to an application page, etc.
I've kind of done a "double-fix" here. Either one on its own should fix the immediate problem, but setting the "shouldCalculateProgress" default based on the current status is more "correct", I think. 
The other fix is purely defensive -- we don't really need it if the first fix is working properly, but I thought it can't hurt to leave it in just in case (and since the result is so unpleasant if it fails)
> #1232 Fix Applicant summary page re-direct loop

- src/containers/List/ListFilters/ListFilters.tsx
Fix #1381 
Smallest PR ever?
Basically just handles the case when the `filter` in `displayableFilters` is not found, which is the case on the first render after changing list page.
> #1381 Fix when changing application list page

- semantic/src/site/globals/site.overrides
- src/components/Dashboard.tsx
- src/utils/graphql/queries/getApplicationsList.query.ts
- src/utils/helpers/list/buildQueryVariables.ts
- src/utils/helpers/utilityFunctions.ts
- src/utils/hooks/useListApplications.tsx
Take 3 🎬 
Based from #1363 
1. This will attempt to help with the delay to load Dashboard page. As noticed by Carl, each single filter would be calling `getApplicationList` each time in order to retrieve each on those account for the applications related to actions. This PR changes that to be one call to getApplicationList per Panel (template). 
2. Also noticed we use pagination was not correctly set, and had the list of applications up to 20. Now changed to be checking the full list (by not passing any pagination parameter)
3. It was required to add a new function to parse into GraphQL query considering an OR statement for each type of filter discovered in the Filters configured for this Dashboard, which was different from what is currently done by `buildFilters` in useApplicationsList. …
> 892B improve filters in dashboard with single query for each panel

- src/components/Review/ReviewSectionRowAction.tsx
Fix #1406 
This was super easy as all the relevant information (i.e assigned sections) was already available in the component.
Note that I've changed this for "Start" and "Continue" review links, but it remains the same (open clicked section) for viewing existing (already submitted) reviews. I assume this makes sense?
> #1406 Open assigned sections when starting or continuing review

- src/containers/Review/ReviewSubmit.tsx
Urgent fix for this.
It's another stale closure problem, @nmadruga -- by defining the ` onConfirm: () => submission()` in the initial instantiation of the "useConfirmationModal", the `submission` function was using the result of "getDecision" from when it was instantiated, not the current one.
So just needed to make sure the confirmation modal got the *current* state by moving it's call inside the "onClick" instead. So now the "getDecision" result will be newly generated and passed to the confirmation modal when "onClick" is run, not when the modal hook is first loaded.
FYI -- if you want to quickly see the effect of this change, just temporarily change the "submission" function to this:
```ts
const submission = async () => {
try {
console.log("Decision will be", getDecision())
// await …
```
> Fix incorrect decision on review submit

- src/containers/Review/ReviewSubmit.tsx
- src/utils/generated/graphql.tsx
- src/utils/graphql/queries/getReviewableQuestionCounts.query.ts
- src/utils/graphql/queries/getReviewableQuestions.query.ts
Required to get proper check for fully approved, otherwise it's basically not checking since `assignedQuestions` may be the same as `reviewedQuestions`, but what we also need to check is if they are fully APPROVED, which so far works by using:
`filter: { or: [{ decision: { equalTo: APPROVE } }, { decision: { equalTo: AGREE } }] }`
> Fix to get assigned and Reviewed elements in current level/stage

- docs/internal/Level-1+-Reviews-and-Changes-Requested.md
- src/components/Review/ReviewSectionRowAssigned.tsx
- src/containers/Review/ReviewPage.tsx
- src/utils/graphql/fragments/reviewAssignment.fragment.ts
- src/utils/helpers/structure/generateReviewSectionActions.ts
- src/utils/hooks/useGetReviewInfo.tsx
- src/utils/hooks/useGetReviewStructureForSection/helpers.tsx
- src/utils/types.ts
Front-end part of [PR #943-part2](https://github.com/openmsupply/conforma-server/pull/955)
- Remove use of `isLocked` for ReviewAssignment in Front-end, not in use
- Also removes related action to ASSIGN_LOCKED
- Easy fix to show "Submitted by" in Final decision (not super related)
> #953B - Part2  generate review assignments action not auto assign final decision

- src/containers/Review/assignment/AssignmentSectionRow.tsx
- src/containers/Review/assignment/AssignmentTab.tsx
- src/containers/Review/assignment/useGetAssignmentOptions.ts
- src/utils/defaultLanguageStrings.ts
- src/utils/generated/graphql.tsx
- src/utils/graphql/fragments/reviewAssignment.fragment.ts
- src/utils/hooks/useGetReviewInfo.tsx
- src/utils/hooks/useLoadAssignments.tsx
- src/utils/types.ts
Part of fix for https://github.com/openmsupply/conforma-server/issues/953
~~Pending: Back-end change to correctly set `availableSections` per ReviewAssignment TODO~~ (Should be done now)
Before we removed `isLocked` the ReviewAssignment for self-assignments knew it couldn't be assigned when the RA was locked (since already assigned to another), now we had to add this property which basically helps with that - and is clearer.
- Added `availableSections` into ReviewAssignment fragment - now this is accessible in query `getReviewInfo`
- Check in `useLoadAssignments` hook to set `isFullyAssigned` - used for AssignAll - Should find if none of ReviewAssignment still have **availableSections** meaning it is Fully assigned...
- Check in `getAssignmentOptions` hook when is Self-assignment should …
> #953 - Fix Self-assign showing after already assigned

- src/containers/TemplateBuilder/evaluatorGui/EvaluationFallback.tsx
- src/containers/TemplateBuilder/evaluatorGui/guiDefinitions.tsx
Fix #1429 
Two main fixes here:
- has a proper `null` value when first switched on
- toggling the switch off now correctly removes the property completely
- values of `null` are preserved in evaluation expression
- can now be disabled (toggle switch) (which you'd want if using global fallback)
Easiest way to test is to just use the "Show as GUI" toggle to compare the state of the UI with what's actually stored in the expression. (And you can see how broken it is when using on develop)
> #1429 Template builder fallbacks fixes

- docs/internal/Element-Type-Specs.md
- src/formElementPlugins/search/src/ApplicationView.tsx
Fix #1440
This was pretty easy to implement, so we can add this to the Import Permit template for @jagoje if we're happy with it.
Adds an additional displayType option -- "input", which keeps the selected value in the input field (only useful for single selections with plain text display).
To see it, use snapshot `Fiji_search_element_updates` in "Snapshot-for-testing-PR" folder. Log in as "adamdewey" (Jess' usual external password) and go to: http://localhost:3000/application/CPR-0012-22/S1/Page1
You'll see a new "Chemical name" field with an input search box (as shown above). Check it in both application view and summary view.
Docs updated accordingly.
> #1440 Search plugin - "input" mode

- src/containers/Dev/Snapshots.tsx
- src/utils/hooks/useConfirmationModal.tsx
In light of my absent-minded blitz of the demo server earlier today, I thought it would be helpful to have some extra warnings when loading a snapshot. I've made it so the warning only shows when you're on a Production build -- that way it should be really obvious.
Warning for overwriting a snapshot too.
Note: I *haven't* added a warning for deletion, as you normally want to delete a whole bunch at once as part of a "clean-up", and it'll be a real hassle to have an extra click for each one. Plus, it shouldn't be a big deal to delete a snapshot as you should always have a copy elsewhere.
@fergie-nz if you want to test this, just temporarily set `const isProductionBuild = !config.isProductionBuild` to reverse the effect, so the confirmations will show locally.
> Extra warnings for snapshots

- src/containers/User/UserArea.tsx
Fix #1446 
Very small change -- just changes the condition for the "Manage" menu appearance to whether there's anything in it or not. Everything else is already working how it should.
This allows us to show the "Remove user..." template in the Manage menu even if the current user doesn't have "isManager" permission.
> #1446 Show manage menu based on contents

- src/components/Admin/Admin.tsx
- src/components/Main/Footer.tsx
- src/config.ts
- src/containers/Dev/UserSelection.tsx
- src/containers/User/Login.tsx
- src/containers/User/NonRegisteredLogin.tsx
- src/containers/User/UserArea.tsx
- src/contexts/UserState.tsx
- src/utils/helpers/fetchUserInfo.ts
- src/utils/hooks/useReferenceDocs.ts
- src/utils/types.ts
Fixes #1445 
- Moves `isAdmin`, `isManager` and `permissionNames` to be in the object for CurrentUser - which can be accessed by the applicationData on Elements
- No need to have preferences to determine the SystemManager in the Front-end anymore.
In case someone would like to test it
[removeUserOrg-5 (2).zip](https://github.com/openmsupply/conforma-web-app/files/10051855/removeUserOrg-5.2.zip)
> #1445 move checks for admin manager inside current user

- semantic/src/site/globals/site.overrides
- src/formElementPlugins/imageDisplay/src/ApplicationView.tsx
- src/formElementPlugins/imageDisplay/src/SummaryView.tsx
Fix to better handle a wider range of logos in the Header bar.
becomes:
I also took the opportunity to improve the Image Display element to allow custom styles to be passed in. This allows us to prevent this kind of thing:
And restrict it to something like this::
> CSS tweaks / Image display improvement

- src/containers/Review/overview/Overview.tsx
Fix #1456 
I've just relaxed the condition a bit so that any application that is EXPIRED or PENDING (i.e. not APPROVED, REJECTED or WITHDRAWN) will show the "Extend deadline" UI.
I think this is okay, but please let me know if you think of any use cases where this is not appropriate.
Can test with Angola ProdReg --- submit an application and the "extend" option should be available to reviewers (it wasn't previously)
(Sorry, I based this off `feature/core-actions` -- I know it should really be from `develop`, but it's too hard to find and use a snapshot in the old state and switch back and forth consistently without messing something up. Hopefully we'll merge the whole feature branch to develop soon anyway)
> #1456 Extend deadline fix

- src/utils/helpers/list/useGetFilterDefinitions.ts
Fixes #1454 
Based on `feature/core-actions` branch - which is planned to be merged by tomorrow 🤞 
Quick fix to allow reviewers to have AssignerAction filter visible on the UI
> #1454 Make AssignerAction filter available on UI

- src/utils/hooks/useGetQuestionReviewHistory.tsx
Fix #1459 
Turned out to be pretty simple. Seems I overlooked (and didn't check) for stages which only have review responses and not application responses, in which case the `allResponsesByStage[stageNumber]` would be not defined yet. So we just create an empty array, like we already do for  the applicationResponses above this block.
> 1459 Fix review history panel

- src/containers/Review/overview/Overview.tsx
Quick fix for problem @jagoje discovered -- the "Extend deadline" button was still visible even though the deadline had been "Cancelled" due to the application being assigned.
Have added additional condition logic so that "cancelled" (i.e. `is_active = false`) deadlines only allow the button to appear if the application is "Expired". This way we can distinguish between applications that have inactive deadlines due to expiration (i.e. can be "unexpired" using this UI), or inactive due to "cancellation" (i.e. the deadline is effectively "gone" and shouldn't be visible in the UI at all)
> Improve deadline extend button condition

- src/LookupTable/components/single/LookUpTable.tsx
Front-end fix required for back-end PR https://github.com/openmsupply/conforma-server/pull/1003
Now that lookup tables can have data types other than `varchar`/`string`, the table display component was crashing as it couldn't handle the "object" data.
This just stringifies it for display.
> #997B Prevent crash when displaying json data in lookup tables

- src/formElementPlugins/listBuilder/src/helpers.ts
Fix [#120T](https://github.com/openmsupply/conforma-templates/issues/120)
This was quite a subtle bug. The mistake was in "anyIncompleteItems" function, we were iterating over `Object.values(currentInput)` and matching it to `inputFields` with the iteration index. However, this is incorrect as the Object values array doesn't get arranged in the same order as the inputFields (since it's from unordered key-value pairs). So the bug was happening due to the "inputField" not being matched to its correct "currentInput.response"
So now I've changed it to iterate over the `inputFields` array instead and match to the correct "currentInput" by code lookup, which keeps them aligned correctly.
I'm surprised it's taking this long for this bug to become apparent!
Everything else (isRequired, etc) seems …
> #120T Fix for listBuilder LOQ bug

- package.json
- src/containers/TemplateBuilder/Templates.tsx
- src/containers/TemplateBuilder/shared/OperationContextHelpers.tsx
Fix for back-end issue https://github.com/openmsupply/conforma-server/issues/1007 (PR: https://github.com/openmsupply/conforma-server/pull/1008)
Turns out that the snapshot file was sometimes being deleted *before* the download had completed, so I've moved the delete command to be part of the export/download button rather than part of the exportTemplate method.
There's not really much of a difference locally (only sometimes problematic), but it's apparent on the servers. 
I've added a pre-release build to https://conforma-demo.msupply.org:50000 so you can test it. Try exporting a template on that server compared with the other ones and notice how only this server reliably exports valid .zips.
> #1007B Template export fix

- docs/internal/config/Element-Type-Specs.md
- src/formElementPlugins/ApplicationViewWrapper.tsx
- src/formElementPlugins/datePicker/pluginConfig.json
- src/formElementPlugins/datePicker/src/ApplicationView.tsx
- src/formElementPlugins/dropdownChoice/src/ApplicationView.tsx
- src/formElementPlugins/listBuilder/pluginConfig.json
- src/formElementPlugins/listBuilder/src/ApplicationView.tsx
- src/formElementPlugins/longText/src/ApplicationView.tsx
- src/formElementPlugins/number/pluginConfig.json
- src/formElementPlugins/number/src/ApplicationView.tsx
- src/formElementPlugins/radioChoice/src/ApplicationView.tsx
- src/formElementPlugins/search/src/ApplicationView.tsx
- src/formElementPlugins/shortText/pluginConfig.json
- src/formElementPlugins/shortText/src/ApplicationView.tsx
- src/formElementPlugins/types.ts
- src/formElementPlugins/useDefault.ts
- src/utils/helpers/utilityFunctions.ts
Fix #1469 #1474 
~~Bit more than I'd hoped to get this working, and I'm still not 100% sold on it. I'd like to do a more robust overhaul of the plugin default handling (to make them all use a common mechanism), but that'll have to wait for now.~~
Ignore the above, I've managed to squeeze in #1474 which makes this a lot nicer and consistent (and easier to read!) There is a new, very simple hook, `useDefault` that the form elements all share, which handles the logic of checking and updating responses based on changing default values. (I've done for all elements that could possible require a default, except for "Checkboxes", since the checkboxes can be defined with a "selected" state in them already. (Admittedly, this would be a bit tricky to make dynamic, but we can add that when we need …
> #1469 #1474 Plugin updates to handle complex pre-filling

- docs/internal/Element-Type-Specs.md
- src/formElementPlugins/dropdownChoice/src/ApplicationView.tsx
Fix #1480 
To see it implemented use the snapshot `dev/snapshots/core_templates_drop_down_multiselect.zip` from Templates repo and got to Section 1, Page 5 -- the first two elements on that page allow multiple selection -- one using objects in the background and one with strings. The string one (first one) also allows a "custom" option to be selected as well.
Be good to get this tested out in current snapshots too -- in particular, please ensure there are no regressions to existing behaviour!
> #1480 Multiple select for Drop-downs

- src/containers/List/ListFilters/ListFilters.tsx
- src/containers/User/UserArea.tsx
- src/utils/types.ts
Front-end part of back-end PR: https://github.com/openmsupply/conforma-server/pull/1027
Just reads the "default_filter_string" provided by the data view API and appends it to the data view url.
To quickly test, load snapshot `/dev/snapshots/Fiji_2023_03_16_1827_default_filters.zip` from templates repo and check out the "Provisional Product Register" data view -- should load filtered to show only *active* products. 
Mess around with the "default_filter_string" value in the data_view definition and see what difference it makes.
> #1026B Default filters for Data Views

- semantic/src/site/globals/site.overrides
- src/containers/DataDisplay/DataViewTable.tsx
- src/containers/List/ListFilters/ListFilters.tsx
- src/containers/List/ListWrapper.tsx
- src/utils/defaultLanguageStrings.ts
- src/utils/hooks/useRouter.tsx
- src/utils/types.ts
Fix #1486 
Requires back-end: https://github.com/openmsupply/conforma-server/pull/1032
To test, go to the Provisional Product Register (Fiji) data view. It should launch with the "isActive=true" filter. Change and update some additional filters, then select "Reset all filters" from Filter button menu. The default `isActive=true` filter should remain (it doesn't in develop). 
Also added a label showing the total result count for all tables (Data Views and Applications List) so user doesn't have to perform mental arithmetic to figure out how many items there are in total for the current table/filter:
See inline comment for more details.
> #1486 Don't remove default filters on reset

- src/utils/helpers/semanticReactMarkdown.tsx
To prevent the problem discovered with @fergie-nz, where the whole table row has an "onClick" event already.
> Prevent Markdown link clicks from propogating event

- src/components/Admin/AdminPreferences.tsx
- src/contexts/Localisation.tsx
- src/utils/defaultLanguageStrings.ts
Fix #1498.
Based off #1497 
This is a much more straightforward (and easier to implement) solution than my original suggestion. We just have an additional "translateMarkdown" (shorthand `tFormat`) method returned from the LanguageProvider, and only language strings that have formatting in them need to be passed to it.
(Will need to make sure you have at least https://github.com/openmsupply/conforma-server/pull/1038 branch in back-end so the "Preferences" page works)
Currently only implemented in one place, the System Preferences.
UPDATE: Added a quick fix for #1503 in here as well.
> #1498 Markdown translation method

- src/formElementPlugins/fileUpload/src/ApplicationView.tsx
- src/formElementPlugins/radioChoice/src/ApplicationView.tsx
Just adds the ability for file upload elements to have a default.
To see it in action, it's applied to the GMP Certificate and Product Registration Certificate fields of the "Product Correction" template (MPCOR2) in Fiji.
> "useDefault" option for File Upload

- src/containers/Review/assignment/AssignmentSectionRow.tsx
- src/containers/Review/overview/Overview.tsx
- src/containers/Review/overview/OverviewTab.tsx
- src/utils/defaultLanguageStrings.ts
Fix https://github.com/openmsupply/conforma-templates/issues/177
Just adds a permanent "View application" button to the Review home page (Overview), and a "Preview application" link to the Assignment interface (only when currently not assigned)
This should only show up when there are assignments to be done:
> #177T (Pre)view applications from review/assign page

- src/containers/TemplateBuilder/Templates.tsx
- src/containers/TemplateBuilder/template/TemplateWrapper.tsx
Fix #1525 
Basic sorting and filtering for Templates list. Should make it a bit easier to find what we're looking for and organise categories, etc.
No need to make a new database query, since we're already pulling the whole data set -- so this is just an in-place rearrangement of the DB result.
> #1525 Sort and Filter for templates list

- package.json
- src/formElementPlugins/datePicker/src/ApplicationView.tsx
- yarn.lock
Fix #1530 
Adds an additional check that input date falls within allowed range.
I've also updated the `react-semantic-ui-datepickers` package to the latest version, so don't forget to `yarn`.
> #1530 Date picker allowed range fix

- src/utils/hooks/useConfirmationModal.tsx
Fix #1539 
Kind of surprising to discover that the Semantic `<Button/>` is still clickable when it's in its "loading" state.
So this just prevents the "onConfirm" method from being called while it's "loading".
Also done a back-end fix to prevent this, too: https://github.com/openmsupply/conforma-server/pull/1058
> #1539 Make Submit button inactive while "loading"

- semantic/src/site/globals/site.overrides
- src/config.ts
- src/containers/Dev/Snapshots.tsx
- src/containers/TemplateBuilder/Templates.tsx
- src/containers/TemplateBuilder/shared/OperationContext.tsx
- src/containers/TemplateBuilder/shared/OperationContextHelpers.tsx
- src/utils/helpers/endpoints/endpointUrlBuilder.ts
- src/utils/helpers/endpoints/types.ts
- src/utils/helpers/utilityFunctions.ts
Fix https://github.com/openmsupply/conforma-server/discussions/1059 (detailed spec/discussion: https://github.com/openmsupply/conforma-server/discussions/1059)
Requires back-end branch from https://github.com/openmsupply/conforma-server/pull/1060
Quite a big face-lift and consolidation for the Snapshots page. It gives more useful stats about each snapshot, include the file size and the archive status:
**Archives**:
- Separate lists for normal Snapshot and "Archive" snapshots
- Show snapshot stats, including file size and archive info
- No need to add time-stamp to snapshot names -- it's automatically appended to downloads
- Creating new snapshot, can specify archive range (or "none" or "full")
- Manually trigger a file archive
- Removed the ability to overwrite a snapshot -- you have to …
> #1059B #1042B File archive management

- package.json
- src/containers/Dev/Snapshots.tsx
- src/containers/TemplateBuilder/Templates.tsx
- src/containers/TemplateBuilder/template/General/General.tsx
- src/containers/TemplateBuilder/useGetTemplates.ts
Fix https://github.com/openmsupply/conforma-server/issues/1068
As per original issue, the following fixes/improvements are implemented:
- More consistent with Snapshots
- Easier to tell what's opened
- Can keep multiple expanded
- Doesn't duplicate the "main" version in the expanded list
- Shows combined application count when collapsed and per-version count when expanded
> #1068B File archive and template version improvements

- semantic/src/site/globals/site.overrides
- semantic/src/site/globals/site.variables
- src/containers/Main/AppWrapper.tsx
- src/contexts/ViewportState.tsx
Fix #1568 
A new context to provide viewport dimensions throughout the app. Also returns a helper `isMobile` value using those dimensions.
Will update as viewport changes, but with a "throttle" time of 300ms to limit re-rendering.
To test/use:
```ts
import { useViewport } from '../contexts/ViewportState' // amend for your own relative path
```
Within React component:
```ts
const {viewport, isMobile} = useViewport()
// For example:
console.log('Width', viewport.width)
console.log('Height', viewport.height)
console.log('Is Mobile?', isMobile)
```
> #1568 Viewport state context

- semantic/src/site/modules/dropdown.overrides
- src/components/List/ApplicationsList.tsx
- src/containers/DataDisplay/DataViewTable.tsx
- src/containers/List/ListWrapper.tsx
- src/utils/defaultLanguageStrings.ts
- src/utils/helpers/list/mapColumnsByRole.ts
- src/utils/tables/TableMobileHeader.tsx
Fix #1570 
Removes the useless mobile header row and replaces it with a custom component to control sorting.
Changes from this:
to this:
Not sure about the best way to display the ascending/descending state, suggestions welcome.
Currently implemented for Application list and Data view tables.
> #1570 Mobile table header/sort bar

- src/components/List/Pagination.tsx
Fix #1567
Using "width" controls doesn't constrain the component, it just chops it off, so I've dynamically adjusted the `siblingRange` and `boundaryRange` props in response to the window width.
Minimum size (320):
Medium size (can handle 1 boundary page, but no siblings):
Full size (non mobile):
> #1567 Pagination component

- semantic/src/site/collections/table.overrides
- Removed borders
- Less spacing between rows
- Long words will wrap and not break viewport
- Could possibly reduce even more gap between rows... matter of taste really.
Didn't reduce padding inside of rows.  I noticed the padding looks bigger on some applications than others.  I think it has to do with empty row data.
wrapping fix:
> 1574 table mobile styles

- src/components/List/ApplicationsList.tsx
- src/containers/DataDisplay/DataViewTable.tsx
- src/utils/tables/TableCellMobileLabelWrapper.tsx
This is little something I didn't quite get right yesterday. When a table cell needs to be hidden, we need to hide the whole cell, but the mobile component I made was *inside* the cell, so the cell itself was still there.
So it meant we got an empty "row", but it still took up height, e.g.
So I've removed the "hide" check from the Mobile wrapper component and just done it separately outside the cell. Not quite as "nice", but works as expected:
> #1574(2) Table mobile extra

- semantic/src/site/globals/site.overrides
- semantic/src/site/globals/site.variables
- src/containers/User/UserArea.tsx
Partly addresses #1586, but doesn't deal with the org dropdown.
Basically, makes things flow better around each other for both mobile and desktop at a wider range of viewport sizes:
- UserMenu button shouldn't wrap, and will expand to fit the name (up to a limit)
- Menu bar shouldn't force org name out of the header (used "position:absolute" for it)
- "Brand Area" logo disappears earlier as the viewport shrinkg
- Header bar size reduced (from 80px to 60)
- Org name fits better into space, and font-size reduced
- Make some margins/padding smaller
> #1586 Header tweaks

- package.json
- semantic/src/site/globals/site.overrides
- src/containers/User/UserArea.tsx
- src/contexts/SystemPrefs.tsx
- yarn.lock
This was quite easy in the end. Just had to figure out how to inject a CSS text string into the head of the document.
You need to run `yarn install` to install one small additional package (see comments).
To get the Angola purple header bar, change the `"style"` value in preferences (Configuration -> System Preferences) to the following actual CSS (instead of our hacky one-off solution)
It'd be good to do something proper with Semantic UI so we could override all the Semantic global variables, but that's quite a bit more complicated, so this will do for now.
> #1590 CSS styles override in preferences

- semantic/src/site/globals/site.overrides
- semantic/src/site/modules/dropdown.overrides
- src/containers/User/UserArea.tsx
- src/utils/defaultLanguageStrings.ts
Fix #1586 
Main purpose is to fix the overly wide organisation menu, from this:
to this:
So I also dropped the text and item size down a bit (as listed in #1579)
> #1586 Other header tweaks

- src/containers/User/UserArea.tsx
- src/contexts/SystemPrefs.tsx
Fix #1596 
Just a quick little addition (for @LaurenceHolding) to allow displaying links in the Help menu. (I've added documentation to the "Preferences" page in back-end.
To test, just add a new property called `"helpLinks"` in preferences -> web, with an array of links, like so:
```
[
{
"text": "Conforma Docs",
"link": "https://docs.conforma.nz/docs/about/introduction/"
}
]
```
> #1075 Links in Help menu

- src/containers/Review/ReviewWrapper.tsx
Hey @guatemartin , ignore this if you've already done it, but this just fixes the tab linking problem picked up in your last PR.
Went back to source, and reversed the tab panes definitions themselves (and removed the other reversals we've added). Then just updated the `get` and `update` query methods to invert the indexing. 
If you've already fixed it, just close this PR. Otherwise merge this into yours and then merge #1608 . Cheers.
> #1604+ Tab fix

- docs/internal/Element-Type-Specs.md
- src/formElementPlugins/search/localisation.json
- src/formElementPlugins/search/src/ApplicationView.tsx
Fix #1623 
4 new parameters (all optional) for the Search element:
- `inputPattern`
- `inputExample`
- `inputErrorMessage`
- `restrictCase`
See updated docs for specifics.
Also, a bit of improvement to existing functionality.
> #1623 Input validation for Search element

- src/components/Application/Navigation.tsx
- src/components/Application/ProgressBar.tsx
- src/contexts/FormElementUpdateTrackerState.tsx
- src/formElementPlugins/ApplicationViewWrapper.tsx
Fix #1547 
Adds an extra property to `FormElementUpdateTrackerState` to hold a record of any elements currently "processing", i.e either re-evaluating properties, or saving. 
Navigation can no longer progress until this value also reports nothing in progress.
> #1547 Better validation before progressing to next page or summary
